### ISSUE TITLE
[Bug] Missing textures.

### ISSUE THREAD

**Issue by SpektacleFR** [isXander/Controlify#100]
### Current Behaviour

Upon installing the mod, I see errors in the textures.  They appear as a black-and-purple square.  This occurs in all custom textures, such as the image of your selected controller, key bind hints in-game, etc.

### Expected Behaviour

Textures should show without issue.  Possibly has to do with referencing non-existent files.  Key bind hints should show the correct button, etc...  not a black-and-purple square.

### Screenshots

![Missing Xbox Controller texture](https://github.com/isXander/Controlify/assets/61282566/be5deadc-2694-4f60-838c-6c42539ec069)
![Missing key bind hints](https://github.com/isXander/Controlify/assets/61282566/75c38feb-ac57-418a-ad70-fa892c785fd6)

### Reproduction Steps

1. Download the most recent version of the mod from Modrinth (GitHub works as well)
2. Install it on Minecraft 1.20.1
3. Launch the game
4. Mess with key binds etc.

### Logs

```shell
https://pastebin.com/4BLgSMUG
```

### Mod Version

1.3.2+1.20

### Controller

Xbox Series Controller

### Bluetooth

- [X] Yes

### Operating System

Windows

### ARM

- [X] Yes

### Additional Information

Also tried using the controller wired, issue persists.

### Just to make sure...

- [X] I have made sure I am using the latest version of Controlify for the latest version of Minecraft.
- [X] I have made sure there are no other issues describing the same problem on the [issue tracker](https://github.com/isXander/Controlify/issues).

**Comment by SpektacleFR** [comment]
Upon log analysis, I've found this chunk of text:
```
[10:50:52] [Render thread/WARN]: Failed to load texture: controlify:textures/gui/joystick/icon.png
java.io.FileNotFoundException: controlify:textures/gui/joystick/icon.png
	at net.minecraft.class_5912.method_43043(class_5912.java:21) ~[client-intermediary.jar:?]
	at java.util.Optional.orElseThrow(Optional.java:403) ~[?:?]
	at net.minecraft.class_5912.getResourceOrThrow(class_5912.java:21) ~[client-intermediary.jar:?]
	at net.minecraft.class_1049$class_4006.method_18156(class_1049.java:83) ~[client-intermediary.jar:?]
	at net.minecraft.class_1049.method_18153(class_1049.java:58) ~[client-intermediary.jar:?]
	at net.minecraft.class_1049.method_4625(class_1049.java:29) ~[client-intermediary.jar:?]
	at net.minecraft.class_1060.method_24303(class_1060.java:97) ~[client-intermediary.jar:?]
	at net.minecraft.class_1060.method_4616(class_1060.java:69) ~[client-intermediary.jar:?]
	at net.minecraft.class_1060.method_4619(class_1060.java:119) ~[client-intermediary.jar:?]
	at com.mojang.blaze3d.systems.RenderSystem._setShaderTexture(RenderSystem.java:1232) ~[client-intermediary.jar:?]
	at com.mojang.blaze3d.systems.RenderSystem.setShaderTexture(RenderSystem.java:1225) ~[client-intermediary.jar:?]
	at net.minecraft.class_332.method_25295(class_332.java:387) ~[client-intermediary.jar:?]
	at net.minecraft.class_332.method_25297(class_332.java:378) ~[client-intermediary.jar:?]
	at net.minecraft.class_332.method_25293(class_332.java:362) ~[client-intermediary.jar:?]
	at net.minecraft.class_332.method_25290(class_332.java:374) ~[client-intermediary.jar:?]
	at dev.isxander.controlify.gui.screen.ControllerCalibrationScreen.method_25394(ControllerCalibrationScreen.java:100) ~[Controlify-1.3.2+1.20.jar:?]
	at net.minecraft.class_437.method_47413(class_437.java:110) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.method_3192(class_757.java:945) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1219) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:802) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:250) ~[client-1.20.1.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.21.jar:?]
```
which states that it failed to load the textures, confirming this issue.

**Comment by isXander** [comment]
Well it seems that your xbox controller is being detected as a joystick rather than a gamepad. Relates to #101

**Comment by SpektacleFR** [comment]
So any input on this?  I'm not exactly sure how the mod works, but is it a system library error or is it a bug directly in the mod?

**Comment by CuteistCat** [comment]
i have it on my xbox elite series 2 [logs](https://mclo.gs/aBDzOXe)

**Comment by seriousfreezing** [comment]
Same Error. 1.19.4 in Windows

**Comment by BeefyAndTheDucks** [comment]
Same error. 1.20.4 Dualshock 4, Windows 11
