### ISSUE TITLE
[Bug] The mod thinks my keyboard is a controller

### ISSUE THREAD

**Issue by VideoGameSmash12** [isXander/Controlify#143]
### Current Behaviour

Every time I try to start my game, the mod mistakenly believes that my keyboard (a Razer BlackWidow V3) is a controller and prompts me to calibrate and configure it. There isn't a way to shut it up so that it doesn't prompt me to configure it on start up.

### Expected Behaviour

I expect my keyboard to be recognized as a keyboard and not a controller

### Screenshots

![image](https://github.com/isXander/Controlify/assets/8041766/372c6224-8a26-4ae7-bf36-24e4be092834)
![image](https://github.com/isXander/Controlify/assets/8041766/e5ddbe9a-d742-44f1-ac03-380aee5a2ce3)

### Reproduction Steps

1. Use a Razer BlackWidow V3 keyboard
2. Start the game

### Logs

```shell
[15:43:50] [Render thread/INFO]: Initializing Controlify...
[15:43:50] [Render thread/INFO]: Loading Controlify config...
[15:43:51] [Render thread/WARN]: No controller found via USB hardware scan! Using SDL if available.
[15:43:51] [Render thread/ERROR]: Failed to fetch controller type!
java.lang.UnsatisfiedLinkError: 'int org.libsdl.SDL.SDL_JoystickGetDeviceVendor(int)'
	at org.libsdl.SDL.SDL_JoystickGetDeviceVendor(Native Method) ~[dev_isxander_sdl2-jni-2.28.2-26-6ebd4fc60eeebe0a.jar:?]
	at dev.isxander.controlify.hid.ControllerHIDService.fetchTypeFromSDL(ControllerHIDService.java:158) ~[Controlify-1.5.0+1.20.jar:?]
	at dev.isxander.controlify.hid.ControllerHIDService.fetchType0(ControllerHIDService.java:101) ~[Controlify-1.5.0+1.20.jar:?]
	at dev.isxander.controlify.hid.ControllerHIDService.fetchType(ControllerHIDService.java:60) ~[Controlify-1.5.0+1.20.jar:?]
	at dev.isxander.controlify.Controlify.discoverControllers(Controlify.java:172) ~[Controlify-1.5.0+1.20.jar:?]
	at dev.isxander.controlify.Controlify.lambda$initializeControlify$0(Controlify.java:94) ~[Controlify-1.5.0+1.20.jar:?]
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863) ~[?:?]
	at java.util.concurrent.CompletableFuture.uniWhenCompleteStage(CompletableFuture.java:887) ~[?:?]
	at java.util.concurrent.CompletableFuture.whenComplete(CompletableFuture.java:2325) ~[?:?]
	at dev.isxander.controlify.Controlify.initializeControlify(Controlify.java:94) ~[Controlify-1.5.0+1.20.jar:?]
	at net.minecraft.class_310.handler$zgb000$controlify$initControlifyNow(class_310.java:3021) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1175) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:802) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:250) ~[minecraft-1.20.1-client.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.21.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71) ~[NewLaunch.jar:?]
[15:43:51] [Render thread/WARN]: No joystick mapping found for controller: 'unknown'
[15:43:51] [Render thread/INFO]: Controller found: Razer Razer BlackWidow V3 Keyboard
[15:43:51] [Render thread/INFO]: Saving Controlify config...
[15:44:12] [Render thread/WARN]: Controlify detected current controller to be constantly giving input and has been disabled.
[15:44:12] [Render thread/INFO]: Saving Controlify config...
```

### Mod Version

1.5.0+1.20

### Controller

https://www.razer.com/gaming-keyboards/razer-blackwidow-v3

### Bluetooth

- [ ] Yes

### Operating System

Linux/SteamOS

### ARM

- [ ] Yes

### Just to make sure...

- [X] I have made sure I am using the latest version of Controlify for the latest version of Minecraft.
- [X] I have made sure there are no other issues describing the same problem on the [issue tracker](https://github.com/isXander/Controlify/issues).

**Comment by isXander** [comment]
Linux is presenting your keyboard as a joystick. You can ignore this.

**Comment by Butterscotch96** [comment]
Isn't that the keyboard with the analog keys that emulate a controller?

**Comment by VideoGameSmash12** [comment]
> You can ignore this.
In that case, is there a way to make the mod completely ignore the keyboard so that it won't show the prompt on start-up?

**Comment by isXander** [comment]
Tracking in libsdl-org/SDL#12758

**Comment by isXander** [comment]
Closing as duplicate of #76
