### ISSUE TITLE
extraalchemy Conflict

### ISSUE THREAD

**Issue by SettingDust** [isXander/Controlify#175]
**Mod Info (fill out the following information)**
- Mod name: extraalchemy
- Mod version: https://modrinth.com/mod/extraalchemy/version/1.10.0

**Describe the problem**
```
java.lang.ExceptionInInitializerError
	at dev.isxander.controlify.bindings.ControllerBindings.<init>(ControllerBindings.java:147)
	at dev.isxander.controlify.controller.Controller$1.<init>(Controller.java:61)
	at dev.isxander.controlify.controller.Controller.<clinit>(Controller.java:60)
	at dev.isxander.controlify.Controlify.currentController(Controlify.java:579)
	at MC//net.minecraft.client.util.InputUtil.modifyReturnValue$ekc000$controlify$modifyIsKeyDown(InputUtil.java:573)
	at MC//net.minecraft.client.util.InputUtil.isKeyPressed(InputUtil.java:473)
	at MC//net.minecraft.client.gui.screen.Screen.hasShiftDown(Screen.java:372)
	at com.replaymod.lib.de.johni0702.minecraft.gui.container.AbstractGuiScreen$MinecraftGuiScreen.keyPressed(AbstractGuiScreen.java:271)
	at com.replaymod.lib.de.johni0702.minecraft.gui.container.VanillaGuiScreen$EventHandler.keyPressed(VanillaGuiScreen.java:252)
	at com.replaymod.lib.de.johni0702.minecraft.gui.versions.callbacks.KeyboardCallback$1.keyPressed(KeyboardCallback.java:12)
	at MC//net.minecraft.client.Keyboard.handler$ldg000$replaymod$keyPressed(Keyboard.java:11108)
	at MC//net.minecraft.client.Keyboard.method_1454(Keyboard.java:395)
	at MC//net.minecraft.client.gui.screen.Screen.wrapScreenError(Screen.java:409)
	at MC//net.minecraft.client.Keyboard.onKey(Keyboard.java:391)
	at MC//net.minecraft.client.Keyboard.method_22678(Keyboard.java:477)
	at MC//net.minecraft.util.thread.ThreadExecutor.execute(ThreadExecutor.java:102)
	at MC//net.minecraft.client.Keyboard.method_22676(Keyboard.java:477)
	at org.lwjgl.glfw.GLFWKeyCallback$Container.invoke(GLFWKeyCallback.java:82)
	at com.moulberry.axiom.editor.CustomImGuiImplGlfw.keyCallback(CustomImGuiImplGlfw.java:272)
	at org.lwjgl.glfw.GLFWKeyCallbackI.callback(GLFWKeyCallbackI.java:44)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3474)
	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(RenderSystem.java:237)
	at MC//net.minecraft.client.MinecraftClient.render(MinecraftClient.java:1244)
	at MC//net.minecraft.client.MinecraftClient.run(MinecraftClient.java:802)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at app//net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at app//net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at app//net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at app//org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:87)
	at app//org.prismlauncher.EntryPoint.listen(EntryPoint.java:127)
	at app//org.prismlauncher.EntryPoint.main(EntryPoint.java:70)
Caused by: java.lang.NullPointerException: PlayerProperties can't be read from null players
	at zabi.minecraft.extraalchemy.entitydata.PlayerProperties.of(PlayerProperties.java:19)
	at MC//net.minecraft.client.texture.StatusEffectSpriteManager.handler$fle000$extraalchemy$injectGetSprite(StatusEffectSpriteManager.java:528)
	at MC//net.minecraft.client.texture.StatusEffectSpriteManager.getSprite(StatusEffectSpriteManager.java)
	at dev.isxander.controlify.bindings.RadialIcons.lambda$addPotionEffects$6(RadialIcons.java:75)
	at java.base@17.0.8/java.util.Iterator.forEachRemaining(Iterator.java:133)
	at com.google.common.collect.Maps$IteratorBasedAbstractMap.forEachEntry(Maps.java:3878)
	at com.google.common.collect.Maps$IteratorBasedAbstractMap$1.forEach(Maps.java:3872)
	at java.base@17.0.8/java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1092)
	at dev.isxander.controlify.bindings.RadialIcons.addPotionEffects(RadialIcons.java:71)
	at dev.isxander.controlify.bindings.RadialIcons.lambda$static$2(RadialIcons.java:36)
	at MC//net.minecraft.util.Util.make(Util.java:432)
	at dev.isxander.controlify.bindings.RadialIcons.<clinit>(RadialIcons.java:24)
	... 32 more
```

**Minecraft Info (please complete the following information):**
 - OS: Windows
 - Minecraft Version: 1.20.1
 - Controlify Version: Controlify-1.7.0-beta.1+1.20

**Comment by isXander** [comment]
When generating sprites for radial menu, an extraalchemy potion is failing because it expects to only be loaded in-game. You should report this there as it is not the issue of Controlify.

**Comment by isXander** [comment]
However I will leave this open as it is regardless a problem.

**Comment by isXander** [comment]
Closing as this old mod conflict appears to be resolved — reopen if you're still seeing this on a current version.
