### ISSUE TITLE
[Bug] Xbox textures arent loaded

### ISSUE THREAD

**Issue by CuteistCat** [isXander/Controlify#190]
### Current Behaviour

I plug in my xbox elite series 2 and i get
`Failed to load texture` when trying to load the xbox controlers texture and it plays default textures

### Expected Behaviour

It would have the Xbox textures loaded

### Reproduction Steps

Plug in xbox controler (on quilt 1.20.1) 
and read the logs or open the controler config and notice that when you bind somethink it displays the "missing texture" icon

### Logs

```shell
to long to show whole logs
'''
	[12:15:27] [Render thread/WARN]:
 Failed to load texture: controlify:textures/gui/joystick/xbox_one/*
java.io.FileNotFoundException: controlify:textures/gui/joystick/xbox_one/*
	at net.minecraft.class_5912.method_43043(class_5912.java:21) ~[transformed-mod-minecraft.i0:0/:?]
	at java.util.Optional.orElseThrow(Optional.java:403) ~[?:?]
	at net.minecraft.class_5912.getResourceOrThrow(class_5912.java:21) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.class_1049$class_4006.method_18156(class_1049.java:83) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.class_1049.method_18153(class_1049.java:58) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.class_1049.method_4625(class_1049.java:29) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.class_1060.method_24303(class_1060.java:97) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.class_1060.method_4616(class_1060.java:69) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.class_1060.method_4619(class_1060.java:119) ~[transformed-mod-minecraft.i0:0/:?]
	at com.mojang.blaze3d.systems.RenderSystem._setShaderTexture(RenderSystem.java:1232) ~[transformed-mod-minecraft.i0:0/:?]
	at com.mojang.blaze3d.systems.RenderSystem.setShaderTexture(RenderSystem.java:1225) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.class_332.method_25295(class_332.java:387) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.class_332.method_25297(class_332.java:378) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.class_332.method_25293(class_332.java:362) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.class_332.method_25290(class_332.java:374) ~[transformed-mod-minecraft.i0:0/:?]
	at dev.isxander.controlify.bindings.JoystickAxisBind.draw(JoystickAxisBind.java:47) ~[transformed-mod-controlify.i0:0/:?]
	at dev.isxander.controlify.gui.controllers.AbstractBindController$AbstractBindControllerElement.drawValueText(AbstractBindController.java:67) ~[transformed-mod-controlify.i0:0/:?]
	at dev.isxander.yacl3.gui.controllers.ControllerWidget.method_25394(ControllerWidget.java:50) ~[transformed-mod-yet-another-config-lib-v3.i0:0/:?]
	at dev.isxander.yacl3.gui.OptionListWidget$OptionEntry.method_25343(OptionListWidget.java:295) ~[transformed-mod-yet-another-config-lib-v3.i0:0/:?]
	at net.minecraft.class_350.method_44397(class_350.java:462) ~[transformed-mod-minecraft.i0:0/:?]
	at dev.isxander.yacl3.gui.ElementListWidgetExt.method_25311(ElementListWidgetExt.java:150) ~[transformed-mod-yet-another-config-lib-v3.i0:0/:?]
	at net.minecraft.class_350.method_25394(class_350.java:227) ~[transformed-mod-minecraft.i0:0/:?]
	at dev.isxander.yacl3.gui.ElementListWidgetExt.method_25394(ElementListWidgetExt.java:58) ~[transformed-mod-yet-another-config-lib-v3.i0:0/:?]
	at dev.isxander.yacl3.gui.tab.ListHolderWidget.method_48579(ListHolderWidget.java:37) ~[transformed-mod-yet-another-config-lib-v3.i0:0/:?]
	at net.minecraft.class_339.method_25394(class_339.java:78) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.class_437.method_25394(class_437.java:120) ~[transformed-mod-minecraft.i0:0/:?]
	at dev.isxander.yacl3.gui.YACLScreen.method_25394(YACLScreen.java:83) ~[transformed-mod-yet-another-config-lib-v3.i0:0/:?]
	at net.minecraft.class_437.method_47413(class_437.java:110) ~[transformed-mod-minecraft.i0:0/:?]

'''
(replace * with aplicable texture)
[full logs](https://mclo.gs/aBDzOXe)
```

### Mod Version

1.7.0-beta.1+1.20

### Controller

Xbox elite series 2

### Bluetooth

- no

### Operating System

Linux/SteamOS

### ARM

-no
### Additional Information

i am using axolotil client

### Just to make sure...

- [ X] I have made sure I am using the latest version of Controlify for the latest version of Minecraft.
- [X ] I have made sure there are no other issues describing the same problem on the [issue tracker](https://github.com/isXander/Controlify/issues).

**Comment by CuteistCat** [comment]
this is a dupe of  #100
