### ISSUE TITLE
[Bug] Incompatability with Create Optimized

### ISSUE THREAD

**Issue by Shotdox** [isXander/Controlify#271]
### Current Behaviour

- After loading the modpack Create Optimized on prism loader, then adding the mod Controlify, the game will load and run until any button on the controller is pressed.. Steam deck, using built in controller.
- If loading Create Optimized modpack by itself it doesnt crash
- If loading Controlify on vanilla with the other required mods it doesnt crash

### Expected Behaviour

It doesnt crash when loading the Controlify mod into the create optimized modpack

### Reproduction Steps

1. Download latest steam deck version, prism loader
2. Add instance of create optimized from CurseForce
3. Edit instance -> Mods -> Download mods

### Logs

```shell
---- Minecraft Crash Report ----
// You're mean.

Time: 2024-04-03 22:04:13
Description: Ticking current controller

java.lang.AbstractMethodError: Receiver class dev.isxander.zoomify.integrations.ControlifyIntegration$SensitivityModifier does not define or inherit an implementation of the resolved method 'abstract float modifyX(float, dev.isxander.controlify.controller.ControllerEntity)' of interface dev.isxander.controlify.api.ingameinput.LookInputModifier.
	at dev.isxander.controlify.api.event.ControlifyEvents$1.modifyX(ControlifyEvents.java:83)
	at dev.isxander.controlify.ingame.InGameInputHandler.handlePlayerLookInput(InGameInputHandler.java:193)
	at dev.isxander.controlify.ingame.InGameInputHandler.inputTick(InGameInputHandler.java:62)
	at java.base/java.util.Optional.ifPresent(Optional.java:178)
	at dev.isxander.controlify.Controlify.tickController(Controlify.java:525)
	at dev.isxander.controlify.Controlify.lambda$tick$34(Controlify.java:474)
	at dev.isxander.controlify.utils.ControllerUtils.wrapControllerError(ControllerUtils.java:28)
	at dev.isxander.controlify.Controlify.lambda$tick$35(Controlify.java:473)
	at java.base/java.util.Optional.ifPresent(Optional.java:178)
	at dev.isxander.controlify.Controlify.tick(Controlify.java:472)
	at net.fabricmc.fabric.api.client.event.lifecycle.v1.ClientTickEvents.lambda$static$0(ClientTickEvents.java:34)
	at net.minecraft.class_310.handler$cbd000$fabric-lifecycle-events-v1$onStartTick(class_310.java:11517)
	at net.minecraft.class_310.method_1574(class_310.java)
	at net.minecraft.class_310.method_1523(class_310.java:1181)
	at net.minecraft.class_310.method_1514(class_310.java:802)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:87)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at dev.isxander.controlify.api.event.ControlifyEvents$1.modifyX(ControlifyEvents.java:83)
	at dev.isxander.controlify.ingame.InGameInputHandler.handlePlayerLookInput(InGameInputHandler.java:193)
	at dev.isxander.controlify.ingame.InGameInputHandler.inputTick(InGameInputHandler.java:62)
	at java.base/java.util.Optional.ifPresent(Optional.java:178)
	at dev.isxander.controlify.Controlify.tickController(Controlify.java:525)
	at dev.isxander.controlify.Controlify.lambda$tick$34(Controlify.java:474)
	at dev.isxander.controlify.utils.ControllerUtils.wrapControllerError(ControllerUtils.java:28)
	at dev.isxander.controlify.Controlify.lambda$tick$35(Controlify.java:473)
	at java.base/java.util.Optional.ifPresent(Optional.java:178)
	at dev.isxander.controlify.Controlify.tick(Controlify.java:472)
	at net.fabricmc.fabric.api.client.event.lifecycle.v1.ClientTickEvents.lambda$static$0(ClientTickEvents.java:34)
	at net.minecraft.class_310.handler$cbd000$fabric-lifecycle-events-v1$onStartTick(class_310.java:11517)

-- Affected controller --
Details:
	Controller name: Steam Deck
	Controller identification: Steam Deck
	Controller type: dev.isxander.controlify.controller.ControllerEntity
Stacktrace:
	at dev.isxander.controlify.utils.ControllerUtils.wrapControllerError(ControllerUtils.java:28)
	at dev.isxander.controlify.Controlify.lambda$tick$35(Controlify.java:473)
	at java.base/java.util.Optional.ifPresent(Optional.java:178)
	at dev.isxander.controlify.Controlify.tick(Controlify.java:472)
	at net.fabricmc.fabric.api.client.event.lifecycle.v1.ClientTickEvents.lambda$static$0(ClientTickEvents.java:34)
	at net.minecraft.class_310.handler$cbd000$fabric-lifecycle-events-v1$onStartTick(class_310.java:11517)
	at net.minecraft.class_310.method_1574(class_310.java)
	at net.minecraft.class_310.method_1523(class_310.java:1181)
	at net.minecraft.class_310.method_1514(class_310.java:802)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:87)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)

-- Affected level --
Details:
	All players: 1 total; [class_746['Shotdox'/225, l='ClientLevel', x=2.50, y=67.00, z=8.50]]
	Chunk stats: 1024, 631
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,68,0), Section: (at 0,4,0 in 0,4,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 1363 game time, 1363 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:458)
	at net.minecraft.class_310.method_1587(class_310.java:2406)
	at net.minecraft.class_310.method_1514(class_310.java:821)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:87)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: vanilla, fabric

-- System Details --
Details:
	Minecraft Version: 1.20.1
	Minecraft Version ID: 1.20.1
	Operating System: Linux (amd64) version 6.1.52-valve16-1-neptune-61
	Java Version: 17.0.9, Flathub
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Flathub
	Memory: 1243445968 bytes (1185 MiB) / 2304770048 bytes (2198 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 8
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Custom APU 0932
	Identifier: AuthenticAMD Family 23 Model 145 Stepping 0
	Microarchitecture: unknown
	Frequency (GHz): -0.00
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: Device
	Graphics card #0 vendor: Advanced Micro Devices, Inc. [AMD/ATI] (0x1002)
	Graphics card #0 VRAM (MB): 258.00
	Graphics card #0 deviceId: 0x1435
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 8431.19
	Virtual memory used (MB): 5948.79
	Swap memory total (MB): 1024.00
	Swap memory used (MB): 0.00
	JVM Flags: 2 total; -Xms512m -Xmx4096m
	Fabric Mods: 
		alternate-current: Alternate Current 1.7.0
		appleskin: AppleSkin 2.5.1+mc1.20
		architectury: Architectury 9.2.14
		badpackets: Bad Packets 0.4.3
		betteradvancements: Better Advancements 0.3.2.162
		betterchunkloading: Better chunk loading mod 1.20.1-3.3
		cardinal-components: Cardinal Components API 5.2.2
			cardinal-components-base: Cardinal Components API (base) 5.2.2
			cardinal-components-block: Cardinal Components API (blocks) 5.2.2
			cardinal-components-chunk: Cardinal Components API (chunks) 5.2.2
			cardinal-components-entity: Cardinal Components API (entities) 5.2.2
			cardinal-components-item: Cardinal Components API (items) 5.2.2
			cardinal-components-level: Cardinal Components API (world saves) 5.2.2
			cardinal-components-scoreboard: Cardinal Components API (scoreboard) 5.2.2
			cardinal-components-world: Cardinal Components API (worlds) 5.2.2
		chunksending: Chunksending Mod 1.20.1-2.8
		cloth-config: Cloth Config v11 11.1.118
			cloth-basic-math: cloth-basic-math 0.6.1
		clumps: Clumps 12.0.0.3
		connectivity: Connectivity Mod 1.20.1-5.4
		controlify: Controlify 2.0.0-beta.2+1.20.1
			dev_isxander_libsdl4j: libsdl4j 3.693c75e-36
			org_hid4java_hid4java: hid4java 0.7.0
			org_quiltmc_quilt-json5: quilt-json5 1.0.3
		controlling: Controlling For Fabric 12.0.2
		create: Create 0.5.1-f-build.1335+mc1.20.1
			com_google_code_findbugs_jsr305: jsr305 3.0.2
			flywheel: Flywheel 0.6.10-2
			milk: Milk Lib 1.2.60
				dripstone_fluid_lib: Dripstone Fluid Lib 3.0.2
			porting_lib_accessors: Porting Lib Accessors 2.3.0+1.20.1
			porting_lib_base: Porting Lib Base 2.3.0+1.20.1
				porting_lib_lazy_registration: Porting Lib Lazy Register 2.3.0+1.20.1
				porting_lib_utility: Porting Lib Utility 2.3.0+1.20.1
			porting_lib_brewing: Porting Lib Brewing 2.3.0+1.20.1
			porting_lib_client_events: Porting Lib Client Events 2.3.0+1.20.1
			porting_lib_entity: Porting Lib Entity 2.3.0+1.20.1
				porting_lib_mixin_extensions: Porting Lib Mixin Extensions 2.3.0+1.20.1
			porting_lib_extensions: Porting Lib Extensions 2.3.0+1.20.1
				porting_lib_attributes: Porting Lib Attributes 2.3.0+1.20.1
				porting_lib_common: Porting Lib Common 2.3.0+1.20.1
			porting_lib_models: Porting Lib Models 2.3.0+1.20.1
				porting_lib_model_loader: Porting Lib Model Loader 2.3.0+1.20.1
			porting_lib_networking: Porting Lib Networking 2.3.0+1.20.1
			porting_lib_obj_loader: Porting Lib Obj Loader 2.3.0+1.20.1
			porting_lib_tags: Porting Lib Tags 3.0
			porting_lib_tool_actions: Porting Lib Tool Actions 2.3.0+1.20.1
			porting_lib_transfer: Porting Lib Transfer 2.3.0+1.20.1
				porting_lib_core: Porting Lib Core 2.3.0+1.20.1
				porting_lib_fluids: Porting Lib Fluids 2.3.0+1.20.1
			reach-entity-attributes: Reach Entity Attributes 2.4.0
			registrate-fabric: Registrate for Fabric 1.3.62-MC1.20.1
				porting_lib_data: Porting Lib Data 2.1.1090+1.20
				porting_lib_model_generators: Porting Lib Model Generators 2.1.1090+1.20
					porting_lib_gametest: Porting Lib GameTest 2.1.1090+1.20
					porting_lib_model_materials: Porting Lib Model Materials 2.1.1090+1.20
		create_enchantment_industry: Create Enchantment Industry 1.2.16
			create_dragon_lib: Create Dragon Lib 1.4.2
		createaddition: Create Crafts & Additions 1.2.3
			team_reborn_energy: Energy 2.3.0
		cullleaves: Cull Leaves 3.2.0
			midnightlib: MidnightLib 1.4.1
		cupboard: cupboard 1.20.1-2.6
		debugify: Debugify 1.20.1+2.0
		deepslatecutting: Deepslate Cutting 1.7.0
		diggusmaximus: Diggus Maximus 1.5.9-1.20
			kyrptconfig: Kyrpt Config 1.5.6-1.20
		dynamic_fps: Dynamic FPS 3.4.2
		entityculling: EntityCulling-Fabric 1.6.2-mc1.20.1
		expandeddelight: Expanded Delight 0.3.0.2
		fabric-api: Fabric API 0.92.0+1.20.1
			fabric-api-base: Fabric API Base 0.4.31+1802ada577
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.36+1802ada577
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.13+1802ada577
			fabric-block-api-v1: Fabric Block API (v1) 1.0.11+1802ada577
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.1+1802ada577
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.41+1802ada577
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.2+1802ada577
			fabric-command-api-v1: Fabric Command API (v1) 1.2.34+f71b366f77
			fabric-command-api-v2: Fabric Command API (v2) 2.2.13+1802ada577
			fabric-commands-v0: Fabric Commands (v0) 0.2.51+df3654b377
			fabric-containers-v0: Fabric Containers (v0) 0.1.64+df3654b377
			fabric-content-registries-v0: Fabric Content Registries (v0) 4.0.11+1802ada577
			fabric-convention-tags-v1: Fabric Convention Tags 1.5.5+1802ada577
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.19+1802ada577
			fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.0.0+de0fd6d177
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 12.3.4+1802ada577
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.54+1802ada577
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.6.0+1c78457f77
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.6.2+1802ada577
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.63+df3654b377
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.40+1802ada577
			fabric-item-api-v1: Fabric Item API (v1) 2.1.28+1802ada577
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.12+1802ada577
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.37+1802ada577
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.35+df3654b377
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.22+1802ada577
			fabric-loot-api-v2: Fabric Loot API (v2) 1.2.1+1802ada577
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.45+9e7660c677
			fabric-message-api-v1: Fabric Message API (v1) 5.1.9+1802ada577
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.50+1802ada577
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 1.0.3+1802ada577
			fabric-models-v0: Fabric Models (v0) 0.4.2+9386d8a777
			fabric-networking-api-v1: Fabric Networking API (v1) 1.3.11+1802ada577
			fabric-networking-v0: Fabric Networking (v0) 0.3.51+df3654b377
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 11.1.3+1802ada577
			fabric-particles-v1: Fabric Particles (v1) 1.1.2+1802ada577
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.21+1802ada577
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.3.3+1802ada577
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.2.1+1802ada577
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.5.1+1802ada577
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.46+df3654b377
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.37+92a0d36777
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.28+1802ada577
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.49+df3654b377
			fabric-rendering-v1: Fabric Rendering (v1) 3.0.8+1802ada577
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.8+1802ada577
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.10+1802ada577
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.8+1802ada577
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.30+1802ada577
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.13+1802ada577
			fabric-transfer-api-v1: Fabric Transfer API (v1) 3.3.4+1802ada577
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 4.3.1+1802ada577
		fabric-language-kotlin: Fabric Language Kotlin 1.10.19+kotlin.1.9.23
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.9.23
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.9.23
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.9.23
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.9.23
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.23.2
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.8.0
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.8.0
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.5.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.6.3
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.6.3
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.6.3
		fabricloader: Fabric Loader 0.15.7
			mixinextras: MixinExtras 0.3.5
		fallingleaves: Falling Leaves 1.15.4
		fallingtree: FallingTree 4.3.4
		farmersdelight: Farmer's Delight 1.20.1-1.4.3
		farmersknives: Farmer's Knives 3.0.2
		ferritecore: FerriteCore 6.0.1
		forgeconfigapiport: Forge Config API Port 8.0.0
		indium: Indium 1.0.30+mc1.20.4
		inventorysorter: Inventory Sorter 1.9.0-1.20
		iris: Iris 1.6.17
			io_github_douira_glsl-transformer: glsl-transformer 2.0.0-pre13
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.11.1
		java: OpenJDK 64-Bit Server VM 17
		krypton: Krypton 0.2.3
			com_velocitypowered_velocity-native: velocity-native 3.2.0-SNAPSHOT
		lazydfu: LazyDFU 0.1.3
		lithium: Lithium 0.11.2
		minecraft: Minecraft 1.20.1
		modmenu: Mod Menu 7.2.2
		mousetweaks: Mouse Tweaks 2.25
		opaccreatesupport: OPAC Create Mod Support 1.3.0
		openpartiesandclaims: Open Parties and Claims 0.20.4
		origins: Origins 1.10.0
			apoli: Apoli 2.9.0
				additionalentityattributes: Additional Entity Attributes 1.3.0+1.20.0
				calio: Calio 1.11.0
				playerabilitylib: Pal 1.8.0
		patchouli: Patchouli 1.20.1-84-FABRIC
			fiber: fiber 0.23.0-2
		railways: Create: Steam 'n' Rails 1.5.3+fabric-mc1.20.1
			mm: Manningham Mills 2.3
		reeses-sodium-options: Reese's Sodium Options 1.7.2+mc1.20.1-build.101
		roughlyenoughitems: Roughly Enough Items 12.0.684
			error_notifier: Error Notifier 1.0.9
		searchables: Searchables 1.0.2
		smoke_suppression: Smoke Suppression 1.0.16
		smoothchunk: Smooth chunk save Mod 1.20.1-3.6
		sodium: Sodium 0.5.8+mc1.20.1
		sodium-extra: Sodium Extra 0.5.4+mc1.20.1-build.115
			caffeineconfig: CaffeineConfig 1.3.0+1.17
			crowdin-translate: CrowdinTranslate 1.4+1.19.3
		spark: spark 1.10.53
		starlight: Starlight 1.1.2+fabric.dbc156f
		terrablender: TerraBlender 3.0.1.4
			com_electronwill_night-config_core: core 3.6.7
			com_electronwill_night-config_toml: toml 3.6.7
		thiccpackets: Extra Thicc Packets 1.17-1.19+
		toms_storage: Tom's Simple Storage Mod 1.6.5
		travelersbackpack: Traveler's Backpack 1.20.1-9.1.9
		wthit: wthit 8.8.0
		xaerominimap: Xaero's Minimap 23.9.7
		xaeroworldmap: Xaero's World Map 1.37.8
		yet_another_config_lib_v3: YetAnotherConfigLib 3.2.2+1.20
			com_twelvemonkeys_common_common-image: common-image 3.10.0-SNAPSHOT
			com_twelvemonkeys_common_common-io: common-io 3.10.0-SNAPSHOT
			com_twelvemonkeys_common_common-lang: common-lang 3.10.0-SNAPSHOT
			com_twelvemonkeys_imageio_imageio-core: imageio-core 3.10.0-SNAPSHOT
			com_twelvemonkeys_imageio_imageio-metadata: imageio-metadata 3.10.0-SNAPSHOT
			com_twelvemonkeys_imageio_imageio-webp: imageio-webp 3.10.0-SNAPSHOT
			org_quiltmc_parsers_gson: gson 0.2.1
			org_quiltmc_parsers_json: json 0.2.1
		yigd: You're in Grave Danger 2.0.0-beta.10
			fabric-permissions-api-v0: fabric-permissions-api 0.2-SNAPSHOT
			libgui: LibGui 8.1.1+1.20.1
				jankson: Jankson 6.0.0+j1.2.3
					blue_endless_jankson: jankson 1.2.3
				libninepatch: LibNinePatch 1.2.0
		zoomify: Zoomify 2.11.2
			com_akuleshov7_ktoml-core-jvm: ktoml-core-jvm 0.4.1
			dev_isxander_settxi_settxi-core: settxi-core 2.10.6
			dev_isxander_settxi_settxi-kotlinx-serialization: settxi-kotlinx-serialization 2.10.6
	Loaded Shaderpack: (off)
	Flywheel Backend: GL33 Instanced Arrays
	Launched Version: 1.20.1
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: AMD Radeon Graphics (radeonsi, vangogh, LLVM 17.0.6, DRM 3.54, 6.1.52-valve16-1-neptune-61) GL version 4.6 (Core Profile) Mesa 24.0.3 (git-c4d371fa7e), AMD
	Window size: 1280x800
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: id=2, source=SHADER COMPILER, type=OTHER, severity=HIGH, message='1:21(24): warning: `FragDistance' used uninitialized' x 1
id=3, source=SHADER COMPILER, type=OTHER, severity=HIGH, message='1:21(24): warning: `FragDistance' used uninitialized' x 1
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Type: Integrated Server (map_client.txt)
	Graphics mode: fancy
	Resource Packs: fabric
	Current Language: en_us
	CPU: 8x AMD Custom APU 0932
	Server Running: true
	Player Count: 1 / 8; [class_3222['Shotdox'/225, l='ServerLevel[Catdog]', x=2.50, y=67.00, z=8.50]]
	Data Packs: vanilla, fabric
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Stable
```

### Mod Version

2.0.0-beta.2+1.20.1

### Controller

Steam deck built in controls

### Bluetooth

- [ ] Yes

### Operating System

Linux/SteamOS

### ARM

- [ ] Yes

### Just to make sure...

- [X] I have made sure I am using the latest version of Controlify for the latest version of Minecraft.
- [X] I have made sure there are no other issues describing the same problem on the [issue tracker](https://github.com/isXander/Controlify/issues).

**Comment by Shotdox** [comment]
The controller works fine in the menus, only crashed when used in game.
Tested mod version 1.6.0+1.20, works perfectly.
Tested mod version 1.7.0-beta.1+1.20, also works perfectly. I will stay with this version for now

**Comment by OKHI233** [comment]
The latest Controlify is incompatible with Zoomify yet on 1.20.1.

**Comment by isXander** [comment]
Closing as this appears to be resolved on current versions — reopen if you're still seeing this
