### ISSUE TITLE
Retain settings between controllers of the same type [Re-open again] [Bug] 

### ISSUE THREAD

**Issue by aekramer** [isXander/Controlify#290]
### Current Behaviour

The issue of controllers of the same type still overwriting settings is unfortunately still happening even after the 2.0.0 beta 3.

The original and subsequent issue was closed as related bugs that may be part of the fix were resolved , however the issue still persists. Unfortunately I do not yet know how to reproduce it consistently, however it still happens every other day that it requires a rebinding of all custom configurations.

Link to previous issues (maybe its time to start a big thread until its actually solved)
https://github.com/isXander/Controlify/issues/256
https://github.com/isXander/Controlify/issues/276

Some additional information:
My Xbox One S Controller is no longer recognized after a firmware update not too long ago, this causes the submit controller data popup when rebooting, not sure if related at all, as I doubt it would be if it was properly logged from the settings file.

### Expected Behaviour

Retain configured settings between controllers of the same type (or even more precisely, the actually same controller is often detected as being new and having to reconfigure it entirely each type, while stock piling the save file with more and more configs each time)

Please provide a way to opt to not use identifiers in the first place and just use the controllers main name (Like Xbox One S Controller) to bind settings to that instead. (Or load add a button to load previous config from same controller type whenever a new controller is detected)

### Reproduction Steps

Simply reconnect a controller or reboot the game every once in a while.

### Mod Version

2.0.0 beta3 + 1.20.4

### Controller

issues

### Bluetooth

- [X] Yes

### Operating System

Windows

### ARM

- [ ] Yes

### Just to make sure...

- [X] I have made sure I am using the latest version of Controlify for the latest version of Minecraft.
- [X] I have made sure there are no other issues describing the same problem on the [issue tracker](https://github.com/isXander/Controlify/issues).

**Comment by isXander** [comment]
Maybe there is a problem that is causing the config to get reset, rather than controller type detection. After repeating the issue, please send the latest.log correlating to that.

**Comment by aekramer** [comment]
> Maybe there is a problem that is causing the config to get reset, rather than controller type detection. After repeating the issue, please send the latest.log correlating to that.

Alright thanks, I'll keep an eye out for it

**Comment by isXander** [comment]
Also, these types of errors are no longer silent. If the config fails to load and resets, you will now get a toast to tell you so, though this case should no longer happen.

**Comment by aekramer** [comment]
> Also, these types of errors are no longer silent. If the config fails to load and resets, you will now get a toast to tell you so, though this case should no longer happen.

Just want to say I really appreciate all the work you put into this already and it's an amazing creation!

**Comment by isXander** [comment]
Thank you! Sorry this issue has been plaguing you for so long!

**Comment by aekramer** [comment]
> Thank you! Sorry this issue has been plaguing you for so long!

Not sure if this is related to the same fix, but just incase for extra note heres a log of a controller crash happening earlier today (the recalibration screen came up but the controller would not work anymore ingame until a reboot)

`[18:36:35] [Render thread/INFO]: Controller disconnected: 'Xbox One S Controller'#SDL-1-HID[VID=0x045e, PID=0x0b20] (null)
[18:36:35] [Render thread/INFO]: Saving Controlify config...
[18:50:10] [Render thread/INFO]: Using SDL to identify controller type.
[18:50:10] [Render thread/WARN]: Controller found via USB hardware scan, but it was not found in the controller identification database! (HID: HID[VID=0x045e, PID=0x0b20])
[18:50:10] [Render thread/ERROR]: Failed to load controller data for 667330d6-8d77-3698-a3cd-0ab6ada0e02a. Resetting to default!
java.lang.NullPointerException: Cannot invoke "dev.isxander.controlify.controller.serialization.ConfigClass.onConfigSaveLoad(dev.isxander.controlify.controller.ControllerEntity)" because "this.instance" is null
	at dev.isxander.controlify.controller.impl.ConfigImpl.deserialize(ConfigImpl.java:54) ~[Controlify-2.0.0-beta.3+1.20.4.jar:?]
	at dev.isxander.controlify.controller.ControllerEntity.deserializeFromObject(ControllerEntity.java:136) ~[Controlify-2.0.0-beta.3+1.20.4.jar:?]
	at dev.isxander.controlify.config.ControlifyConfig.applyControllerConfig(ControlifyConfig.java:177) ~[Controlify-2.0.0-beta.3+1.20.4.jar:?]
	at dev.isxander.controlify.config.ControlifyConfig.loadOrCreateControllerData(ControlifyConfig.java:165) ~[Controlify-2.0.0-beta.3+1.20.4.jar:?]
	at dev.isxander.controlify.controllermanager.AbstractControllerManager.onControllerConnected(AbstractControllerManager.java:82) ~[Controlify-2.0.0-beta.3+1.20.4.jar:?]
	at dev.isxander.controlify.controllermanager.SDLControllerManager.lambda$tick$0(SDLControllerManager.java:73) ~[Controlify-2.0.0-beta.3+1.20.4.jar:?]
	at dev.isxander.controlify.utils.ControllerUtils.wrapControllerError(ControllerUtils.java:28) ~[Controlify-2.0.0-beta.3+1.20.4.jar:?]
	at dev.isxander.controlify.controllermanager.SDLControllerManager.lambda$tick$1(SDLControllerManager.java:73) ~[Controlify-2.0.0-beta.3+1.20.4.jar:?]
	at java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
	at dev.isxander.controlify.controllermanager.SDLControllerManager.tick(SDLControllerManager.java:72) ~[Controlify-2.0.0-beta.3+1.20.4.jar:?]
	at dev.isxander.controlify.Controlify.tick(Controlify.java:491) ~[Controlify-2.0.0-beta.3+1.20.4.jar:?]
	at net.fabricmc.fabric.api.client.event.lifecycle.v1.ClientTickEvents.lambda$static$0(ClientTickEvents.java:34) ~[fabric-lifecycle-events-v1-2.3.0+a67ffb5d4f-b1011876dc990029.jar:?]
	at net.minecraft.class_310.handler$zoe000$fabric-lifecycle-events-v1$onStartTick(class_310.java:8272) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1574(class_310.java) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1289) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:888) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:265) ~[minecraft-1.20.4-client.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.7.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:243) ~[NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:278) ~[NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) ~[NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) ~[NewLaunch.jar:?]
[18:50:10] [Render thread/INFO]: Saving Controlify config...
[18:50:10] [Render thread/INFO]: Controller connected: 'Xbox One S Controller'#SDL-2-HID[VID=0x045e, PID=0x0b20] (null)`

**Comment by isXander** [comment]
This has been fixed
