### ISSUE TITLE
[Bug] Clicking Circle in the Main Menu Crashes

### ISSUE THREAD

**Issue by TheCrafter8000** [isXander/Controlify#305]
### Current Behaviour

When you press Circle in the Main Menu is crashes the game instead

### Expected Behaviour

Not sure if there is supposed to be a option menu that pops up or just close the game normally

### Reproduction Steps

Be on the Main Menu
Connect a Dualsense Controller
Click Circle

### Logs

```shell
---- Minecraft Crash Report ----
// This doesn't make any sense!

Time: 2024-05-03 00:51:35
Description: Ticking current controller

java.util.NoSuchElementException: No value present
	at java.base/java.util.Optional.orElseThrow(Optional.java:377)
	at dev.isxander.controlify.screenop.compat.vanilla.TitleScreenProcessor.handleButtons(TitleScreenProcessor.java:19)
	at dev.isxander.controlify.screenop.ScreenProcessor.onControllerUpdate(ScreenProcessor.java:51)
	at dev.isxander.controlify.Controlify.tickController(Controlify.java:548)
	at dev.isxander.controlify.Controlify.lambda$tick$35(Controlify.java:497)
	at dev.isxander.controlify.utils.ControllerUtils.wrapControllerError(ControllerUtils.java:28)
	at dev.isxander.controlify.Controlify.lambda$tick$36(Controlify.java:496)
	at java.base/java.util.Optional.ifPresent(Optional.java:178)
	at dev.isxander.controlify.Controlify.tick(Controlify.java:495)
	at net.fabricmc.fabric.api.client.event.lifecycle.v1.ClientTickEvents.lambda$static$0(ClientTickEvents.java:34)
	at net.minecraft.class_310.handler$bbn000$fabric-lifecycle-events-v1$onStartTick(class_310.java:9772)
	at net.minecraft.class_310.method_1574(class_310.java)
	at net.minecraft.class_310.method_1523(class_310.java:1289)
	at net.minecraft.class_310.method_1514(class_310.java:888)
	at net.minecraft.client.main.Main.main(Main.java:265)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
```

### Mod Version

Controlify-2.0.0-beta.5+1.20.4

### Controller

DualSense

### Bluetooth

- [X] Yes

### Operating System

Windows

### ARM

- [ ] Yes

### Just to make sure...

- [X] I have made sure I am using the latest version of Controlify for the latest version of Minecraft.
- [X] I have made sure there are no other issues describing the same problem on the [issue tracker](https://github.com/isXander/Controlify/issues).

**Comment by isXander** [comment]
Update to the latest
