### ISSUE TITLE
[Controller Request] Nintendo Switch Joy-Con ( L/R )

### ISSUE THREAD

**Issue by pengtao6993** [isXander/Controlify#368]
**Controller name**

Nintendo Switch Joy-Con ( L/R )

**Controller VID & PID**

BTHENUM\Dev_58B03E956092 (Left)
BTHENUM\Dev_58B03E9591B2 (Right)

//
If I connects them within Controllify,Minecraft crash.

crash report:

```
 ---- Minecraft Crash Report ----
// This doesn't make any sense!

Time: 2024-07-06 12:21:36
Description: Creating controller #SDL-1

java.lang.IllegalStateException: Could not open joystick: Joystick 1 not found
	at dev.isxander.controlify.driver.sdl.SDL3JoystickDriver.<init>(SDL3JoystickDriver.java:49)
	at dev.isxander.controlify.controllermanager.SDLControllerManager.createController(SDLControllerManager.java:131)
	at dev.isxander.controlify.controllermanager.AbstractControllerManager.tryCreate(AbstractControllerManager.java:57)
	at dev.isxander.controlify.controllermanager.SDLControllerManager.tick(SDLControllerManager.java:75)
	at dev.isxander.controlify.Controlify.tick(Controlify.java:493)
	at net.fabricmc.fabric.api.client.event.lifecycle.v1.ClientTickEvents.lambda$static$0(ClientTickEvents.java:34)
	at net.minecraft.class_310.handler$zim000$fabric-lifecycle-events-v1$onStartTick(class_310.java:7178)
	at net.minecraft.class_310.method_1574(class_310.java)
	at net.minecraft.class_310.method_1523(class_310.java:1246)
	at net.minecraft.class_310.method_1514(class_310.java:882)
	at net.minecraft.client.main.Main.main(Main.java:256)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at oolloo.jlw.Wrapper.invokeMain(Wrapper.java:71)
	at oolloo.jlw.Wrapper.main(Wrapper.java:51)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at dev.isxander.controlify.driver.sdl.SDL3JoystickDriver.<init>(SDL3JoystickDriver.java:49)
	at dev.isxander.controlify.controllermanager.SDLControllerManager.createController(SDLControllerManager.java:131)
	at dev.isxander.controlify.controllermanager.AbstractControllerManager.tryCreate(AbstractControllerManager.java:57)
	at dev.isxander.controlify.controllermanager.SDLControllerManager.tick(SDLControllerManager.java:75)
	at dev.isxander.controlify.Controlify.tick(Controlify.java:493)
	at net.fabricmc.fabric.api.client.event.lifecycle.v1.ClientTickEvents.lambda$static$0(ClientTickEvents.java:34)
	at net.minecraft.class_310.handler$zim000$fabric-lifecycle-events-v1$onStartTick(class_310.java:7178)

-- Controller Info --
Details:
	Unique controller ID: SDL-1
	Controller identification: ControllerType[friendlyName=null, mappingId=default, namespace=controlify:default, forceJoystick=false, dontLoad=false]
	HID path: N/A
	HID service status: Enabled
	System name: N/A
Stacktrace:
	at dev.isxander.controlify.controllermanager.AbstractControllerManager.tryCreate(AbstractControllerManager.java:57)
	at dev.isxander.controlify.controllermanager.SDLControllerManager.tick(SDLControllerManager.java:75)
	at dev.isxander.controlify.Controlify.tick(Controlify.java:493)
	at net.fabricmc.fabric.api.client.event.lifecycle.v1.ClientTickEvents.lambda$static$0(ClientTickEvents.java:34)
	at net.minecraft.class_310.handler$zim000$fabric-lifecycle-events-v1$onStartTick(class_310.java:7178)
	at net.minecraft.class_310.method_1574(class_310.java)
	at net.minecraft.class_310.method_1523(class_310.java:1246)
	at net.minecraft.class_310.method_1514(class_310.java:882)
	at net.minecraft.client.main.Main.main(Main.java:256)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at oolloo.jlw.Wrapper.invokeMain(Wrapper.java:71)
	at oolloo.jlw.Wrapper.main(Wrapper.java:51)

-- Uptime --
Details:
	JVM uptime: 29.866s
	Wall uptime: 12.471s
	High-res time: 8.146s
	Client ticks: 51 ticks / 2.550s
Stacktrace:
	at net.minecraft.class_310.method_1587(class_310.java:2501)
	at net.minecraft.class_310.method_54580(class_310.java:949)
	at net.minecraft.class_310.method_1514(class_310.java:902)
	at net.minecraft.client.main.Main.main(Main.java:256)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at oolloo.jlw.Wrapper.invokeMain(Wrapper.java:71)
	at oolloo.jlw.Wrapper.main(Wrapper.java:51)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: vanilla, fabric, caffeineconfig, controlify, fabric-api, fabric-api-base, fabric-api-lookup-api-v1, fabric-biome-api-v1, fabric-block-api-v1, fabric-block-view-api-v2, fabric-blockrenderlayer-v1, fabric-client-tags-api-v1, fabric-command-api-v1, fabric-command-api-v2, fabric-commands-v0, fabric-content-registries-v0, fabric-convention-tags-v1, fabric-convention-tags-v2, fabric-crash-report-info-v1, fabric-data-attachment-api-v1, fabric-data-generation-api-v1, fabric-dimensions-v1, fabric-entity-events-v1, fabric-events-interaction-v0, fabric-game-rule-api-v1, fabric-item-api-v1, fabric-item-group-api-v1, fabric-key-binding-api-v1, fabric-keybindings-v0, fabric-lifecycle-events-v1, fabric-loot-api-v2, fabric-message-api-v1, fabric-model-loading-api-v1, fabric-networking-api-v1, fabric-object-builder-api-v1, fabric-particles-v1, fabric-recipe-api-v1, fabric-registry-sync-v0, fabric-renderer-api-v1, fabric-renderer-indigo, fabric-renderer-registries-v1, fabric-rendering-data-attachment-v1, fabric-rendering-fluids-v1, fabric-rendering-v0, fabric-rendering-v1, fabric-resource-conditions-api-v1, fabric-resource-loader-v0, fabric-screen-api-v1, fabric-screen-handler-api-v1, fabric-sound-api-v1, fabric-transfer-api-v1, fabric-transitive-access-wideners-v1, fabricloader, firstperson, iris, reeses-sodium-options, sodium, sodium-extra, xaerominimap, xaeroworldmap, yet_another_config_lib_v3

-- System Details --
Details:
	Minecraft Version: 1.21
	Minecraft Version ID: 1.21
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 21.0.1, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 405842392 bytes (387 MiB) / 973078528 bytes (928 MiB) up to 6442450944 bytes (6144 MiB)
	CPUs: 4
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Xeon(R) CPU E3-1226 v3 @ 3.30GHz
	Identifier: Intel64 Family 6 Model 60 Stepping 3
	Microarchitecture: Haswell (Client)
	Frequency (GHz): 3.30
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 4
	Graphics card #0 name: NVIDIA Quadro K620
	Graphics card #0 vendor: NVIDIA
	Graphics card #0 VRAM (MiB): 2048.00
	Graphics card #0 deviceId: VideoController1
	Graphics card #0 versionInfo: 31.0.15.3799
	Graphics card #1 name: NVIDIA GeForce GT 630
	Graphics card #1 vendor: NVIDIA
	Graphics card #1 VRAM (MiB): 2048.00
	Graphics card #1 deviceId: VideoController2
	Graphics card #1 versionInfo: 30.0.14.7212
	Graphics card #2 name: NVIDIA Quadro K620
	Graphics card #2 vendor: NVIDIA
	Graphics card #2 VRAM (MiB): 2048.00
	Graphics card #2 deviceId: VideoController3
	Graphics card #2 versionInfo: 31.0.15.3799
	Graphics card #3 name: Intel(R) HD Graphics 4400
	Graphics card #3 vendor: Intel Corporation
	Graphics card #3 VRAM (MiB): 1024.00
	Graphics card #3 deviceId: VideoController4
	Graphics card #3 versionInfo: 20.19.15.5171
	Graphics card #4 name: Intel(R) HD Graphics P4600/P4700
	Graphics card #4 vendor: Intel Corporation
	Graphics card #4 VRAM (MiB): 1024.00
	Graphics card #4 deviceId: VideoController5
	Graphics card #4 versionInfo: 20.19.15.5171
	Graphics card #5 name: Microsoft Basic Display Adapter
	Graphics card #5 vendor: Microsoft
	Graphics card #5 VRAM (MiB): 0.00
	Graphics card #5 deviceId: VideoController6
	Graphics card #5 versionInfo: 10.0.22621.1
	Graphics card #6 name: NVIDIA Tesla M4
	Graphics card #6 vendor: NVIDIA
	Graphics card #6 VRAM (MiB): 4096.00
	Graphics card #6 deviceId: VideoController7
	Graphics card #6 versionInfo: 31.0.15.5178
	Memory slot #0 capacity (MiB): 4096.00
	Memory slot #0 clockSpeed (GHz): 1.60
	Memory slot #0 type: DDR3
	Memory slot #1 capacity (MiB): 4096.00
	Memory slot #1 clockSpeed (GHz): 1.60
	Memory slot #1 type: DDR3
	Memory slot #2 capacity (MiB): 4096.00
	Memory slot #2 clockSpeed (GHz): 1.60
	Memory slot #2 type: DDR3
	Memory slot #3 capacity (MiB): 4096.00
	Memory slot #3 clockSpeed (GHz): 1.60
	Memory slot #3 type: DDR3
	Virtual memory max (MiB): 19452.74
	Virtual memory used (MiB): 6318.60
	Swap memory total (MiB): 3200.00
	Swap memory used (MiB): 1995.05
	Space in storage for jna.tmpdir (MiB): available: 111595.28, total: 205721.86
	Space in storage for org.lwjgl.system.SharedLibraryExtractPath (MiB): available: 111595.28, total: 205721.86
	Space in storage for io.netty.native.workdir (MiB): available: 111595.28, total: 205721.86
	Space in storage for java.io.tmpdir (MiB): available: 89279.75, total: 215788.44
	Space in storage for workdir (MiB): available: 111595.28, total: 205721.86
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmn921m -Xmx6144m
	Fabric Mods: 
		controlify: Controlify 2.0.0-beta.13+1.21-fabric
			dev_isxander_libsdl4j: libsdl4j 3.6896c4c-38
			org_hid4java_hid4java: hid4java 0.7.0
			org_quiltmc_parsers_gson: gson 0.3.0
			org_quiltmc_parsers_json: json 0.3.0
		fabric-api: Fabric API 0.100.4+1.21
			fabric-api-base: Fabric API Base 0.4.42+6573ed8cd1
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.67+b5597344d1
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.28+6fc22b99d1
			fabric-block-api-v1: Fabric Block API (v1) 1.0.22+0af3f5a7d1
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.10+6573ed8cd1
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.52+0af3f5a7d1
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.15+6573ed8cd1
			fabric-command-api-v1: Fabric Command API (v1) 1.2.48+f71b366fd1
			fabric-command-api-v2: Fabric Command API (v2) 2.2.27+6a6dfa19d1
			fabric-commands-v0: Fabric Commands (v0) 0.2.65+df3654b3d1
			fabric-content-registries-v0: Fabric Content Registries (v0) 8.0.14+b5597344d1
			fabric-convention-tags-v1: Fabric Convention Tags 2.0.15+7f945d5bd1
			fabric-convention-tags-v2: Fabric Convention Tags (v2) 2.3.2+78017270d1
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.29+0af3f5a7d1
			fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.1.24+6a6dfa19d1
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 20.2.9+16c4ae25d1
			fabric-dimensions-v1: Fabric Dimensions API (v1) 4.0.0+6fc22b99d1
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.6.12+6fc22b99d1
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.7.10+e633f883d1
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.52+6573ed8cd1
			fabric-item-api-v1: Fabric Item API (v1) 11.0.0+afdfc921d1
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.1.2+78017270d1
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.47+0af3f5a7d1
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.45+df3654b3d1
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.3.11+8f3583aed1
			fabric-loot-api-v2: Fabric Loot API (v2) 3.0.11+6573ed8cd1
			fabric-message-api-v1: Fabric Message API (v1) 6.0.13+6573ed8cd1
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 2.0.0+fe474d6bd1
			fabric-networking-api-v1: Fabric Networking API (v1) 4.2.0+ab7edbacd1
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 15.1.12+d1321076d1
			fabric-particles-v1: Fabric Particles (v1) 4.0.2+6573ed8cd1
			fabric-recipe-api-v1: Fabric Recipe API (v1) 5.0.10+65089712d1
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 5.0.23+78017270d1
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.3.0+0ae0b97dd1
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.6.5+48fb1586d1
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.67+df3654b3d1
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.48+73761d2ed1
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.1.6+b5597344d1
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.70+df3654b3d1
			fabric-rendering-v1: Fabric Rendering (v1) 5.0.4+5a8c785ed1
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 4.2.1+d153f344d1
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 1.1.5+78017270d1
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.24+b5597344d1
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.80+b5597344d1
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.23+6573ed8cd1
			fabric-transfer-api-v1: Fabric Transfer API (v1) 5.1.15+3dccd343d1
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 6.0.12+6573ed8cd1
		fabricloader: Fabric Loader 0.15.11
			mixinextras: MixinExtras 0.3.5
		firstperson: FirstPerson 2.4.3
		iris: Iris 1.7.3+mc1.21
			io_github_douira_glsl-transformer: glsl-transformer 2.0.1
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.13.1
		java: Java HotSpot(TM) 64-Bit Server VM 21
		minecraft: Minecraft 1.21
		reeses-sodium-options: Reese's Sodium Options 1.7.2+mc1.21
		sodium: Sodium 0.5.11+mc1.21
		sodium-extra: Sodium Extra 0.5.7+mc1.21
			caffeineconfig: CaffeineConfig 1.3.0+1.17
		xaerominimap: Xaero's Minimap 24.2.1
		xaeroworldmap: Xaero's World Map 1.38.8
		yet_another_config_lib_v3: YetAnotherConfigLib 3.5.0+1.21-fabric
			com_twelvemonkeys_common_common-image: common-image 3.10.0
			com_twelvemonkeys_common_common-io: common-io 3.10.0
			com_twelvemonkeys_common_common-lang: common-lang 3.10.0
			com_twelvemonkeys_imageio_imageio-core: imageio-core 3.10.0
			com_twelvemonkeys_imageio_imageio-metadata: imageio-metadata 3.10.0
			com_twelvemonkeys_imageio_imageio-webp: imageio-webp 3.10.0
	Loaded Shaderpack: (off)
	Launched Version: 1.21-Fabric 0.15.11
	Launcher name: PCL
	Backend library: LWJGL version 3.3.3-snapshot
	Backend API: Tesla M4/PCIe/SSE2 GL version 3.2.0 NVIDIA 551.78, NVIDIA Corporation
	Window size: 958x508
	GFLW Platform: win32
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Is Modded: Definitely; Client brand changed to 'fabric'
	Universe: 400921fb54442d18
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Render Distance: 12/12 chunks
	Resource Packs: vanilla, fabric, caffeineconfig, controlify, fabric-api, fabric-api-base, fabric-api-lookup-api-v1, fabric-biome-api-v1, fabric-block-api-v1, fabric-block-view-api-v2, fabric-blockrenderlayer-v1, fabric-client-tags-api-v1, fabric-command-api-v1, fabric-command-api-v2, fabric-commands-v0, fabric-content-registries-v0, fabric-convention-tags-v1, fabric-convention-tags-v2, fabric-crash-report-info-v1, fabric-data-attachment-api-v1, fabric-data-generation-api-v1, fabric-dimensions-v1, fabric-entity-events-v1, fabric-events-interaction-v0, fabric-game-rule-api-v1, fabric-item-api-v1, fabric-item-group-api-v1, fabric-key-binding-api-v1, fabric-keybindings-v0, fabric-lifecycle-events-v1, fabric-loot-api-v2, fabric-message-api-v1, fabric-model-loading-api-v1, fabric-networking-api-v1, fabric-object-builder-api-v1, fabric-particles-v1, fabric-recipe-api-v1, fabric-registry-sync-v0, fabric-renderer-api-v1, fabric-renderer-indigo, fabric-renderer-registries-v1, fabric-rendering-data-attachment-v1, fabric-rendering-fluids-v1, fabric-rendering-v0, fabric-rendering-v1, fabric-resource-conditions-api-v1, fabric-resource-loader-v0, fabric-screen-api-v1, fabric-screen-handler-api-v1, fabric-sound-api-v1, fabric-transfer-api-v1, fabric-transitive-access-wideners-v1, fabricloader, firstperson, iris, reeses-sodium-options, sodium, sodium-extra, xaerominimap (incompatible), xaeroworldmap (incompatible), yet_another_config_lib_v3 (incompatible)
	Current Language: zh_cn
	Locale: zh_CN
	System encoding: GBK
	File encoding: UTF-8
	CPU: 4x Intel(R) Xeon(R) CPU E3-1226 v3 @ 3.30GHz


```

**Comment by isXander** [comment]
Closing as this old Joy-Con crash appears to be resolved — reopen if you're still seeing this on a current version.
