### ISSUE TITLE
Crash On Opening Creative Menu (Item group has no page)

### ISSUE THREAD

**Issue by Roritamashi** [isXander/Controlify#369]
Is just in creative, idk if this is because of this mod as it show in the part of the log below

[16:10:42] [Render thread/ERROR]:
 Unreported exception thrown!
java.lang.IllegalStateException: Item group has no page
	at net.minecraft.class_1761.getPage(class_1761.java:1096) ~[client-intermediary.jar:?]
	at dev.isxander.controlify.platform.client.fabric.FAPIImplCreativeTabHelper.getPageForTab(FAPIImplCreativeTabHelper.java:75) ~[Controlify-2.0.0-beta.13+1.20.4-fabric.jar:?]
	at dev.isxander.controlify.platform.client.fabric.FAPIImplCreativeTabHelper.lambda$pageHasAnyTab$2(FAPIImplCreativeTabHelper.java:90) ~[Controlify-2.0.0-beta.13+1.20.4-fabric.jar:?]
	at java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90) ~[?:?]
	at java.util.AbstractList$RandomAccessSpliterator.tryAdvance(AbstractList.java:706) ~[?:?]
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129) ~[?:?]
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230) ~[?:?]
	at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.anyMatch(ReferencePipeline.java:632) ~[?:?]
	at dev.isxander.controlify.platform.client.fabric.FAPIImplCreativeTabHelper.pageHasAnyTab(FAPIImplCreativeTabHelper.java:90) ~[Controlify-2.0.0-beta.13+1.20.4-fabric.jar:?]
	at dev.isxander.controlify.platform.client.fabric.FAPIImplCreativeTabHelper.<init>(FAPIImplCreativeTabHelper.java:27) ~[Controlify-2.0.0-beta.13+1.20.4-fabric.jar:?]
	at dev.isxander.controlify.platform.client.fabric.FabricPlatformClientImpl.createCreativeTabHelper(FabricPlatformClientImpl.java:110) ~[Controlify-2.0.0-beta.13+1.20.4-fabric.jar:?]
	at dev.isxander.controlify.platform.client.PlatformClientUtil.createCreativeTabHelper(PlatformClientUtil.java:71) ~[Controlify-2.0.0-beta.13+1.20.4-fabric.jar:?]
	at dev.isxander.controlify.screenop.compat.vanilla.CreativeModeInventoryScreenProcessor.<init>(CreativeModeInventoryScreenProcessor.java:21) ~[Controlify-2.0.0-beta.13+1.20.4-fabric.jar:?]
	at net.minecraft.class_481.<init>(class_481.java:215) ~[client-intermediary.jar:?]
	at net.minecraft.class_490.method_25426(class_490.java:51) ~[client-intermediary.jar:?]
	at net.minecraft.class_437.method_25423(class_437.java:298) ~[client-intermediary.jar:?]

**Comment by N0aW** [comment]
Most likely a mod incompat, try to see if you can replicate it with only Controlify
