### ISSUE TITLE
[Bug] Crashes anytime I try opening the settings.

### ISSUE THREAD

**Issue by BarnoWarno** [isXander/Controlify#386]
### Current Behaviour

Crashes anytime I try opening the controller settings... don't have any mods appart from the few requested compatibility mobs. I am running Fabric and MacOS. I can play though, as long as I don't open the settings tab. I'm using a Series X controller !

Mods installed are : YetAnotherConigLib, Fabric API, Mod Menu, Text Placeholder API and Controlify.
 I'm running minecraft version 1.20.4 on Fabric Launcher. 

This is code error : 255

### Expected Behaviour

Should be able to play and access the settings...

### Reproduction Steps

Lauch minecraft with mod in it, control settings, select controlify settings, crash... it always shows a "loading world" screen for a split second before the game crashes and exits.

### Logs

```shell
---- Minecraft Crash Report ----
// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 2024-07-24 14:40:04
Description: Ticking current controller

java.lang.RuntimeException: Mixin transformation of dev.isxander.yacl3.gui.YACLScreen$CategoryTab failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	at dev.isxander.yacl3.gui.YACLScreen.lambda$init$4(YACLScreen.java:89)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.Collections$2.tryAdvance(Collections.java:4853)
	at java.base/java.util.Collections$2.forEachRemaining(Collections.java:4861)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575)
	at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616)
	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:622)
	at java.base/java.util.stream.ReferencePipeline.toList(ReferencePipeline.java:627)
	at dev.isxander.yacl3.gui.YACLScreen.method_25426(YACLScreen.java:90)
	at net.minecraft.class_437.method_25423(class_437.java:298)
	at net.minecraft.class_310.method_1507(class_310.java:1187)
	at dev.isxander.controlify.gui.screen.ControllerCarouselScreen.lambda$init$4(ControllerCarouselScreen.java:95)
	at net.minecraft.class_4185.method_25306(class_4185.java:95)
	at dev.isxander.controlify.screenop.compat.vanilla.AbstractButtonComponentProcessor.overrideControllerButtons(AbstractButtonComponentProcessor.java:20)
	at dev.isxander.controlify.screenop.ScreenProcessor.handleComponentButtonOverride(ScreenProcessor.java:178)
	at dev.isxander.controlify.screenop.ScreenProcessor.onControllerUpdate(ScreenProcessor.java:48)
	at dev.isxander.controlify.Controlify.tickController(Controlify.java:498)
	at dev.isxander.controlify.Controlify.lambda$tick$27(Controlify.java:458)
	at dev.isxander.controlify.utils.ControllerUtils.wrapControllerError(ControllerUtils.java:37)
	at dev.isxander.controlify.Controlify.lambda$tick$28(Controlify.java:457)
	at java.base/java.util.Optional.ifPresent(Optional.java:178)
	at dev.isxander.controlify.Controlify.tick(Controlify.java:456)
	at net.fabricmc.fabric.api.client.event.lifecycle.v1.ClientTickEvents.lambda$static$0(ClientTickEvents.java:34)
	at net.minecraft.class_310.handler$zil000$fabric-lifecycle-events-v1$onStartTick(class_310.java:6772)
	at net.minecraft.class_310.method_1574(class_310.java)
	at net.minecraft.class_310.method_1523(class_310.java:1289)
	at net.minecraft.class_310.method_1514(class_310.java:888)
	at net.minecraft.client.main.Main.main(Main.java:265)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422)
	... 38 more
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [controlify.mixins.json:compat.yacl.YACLScreenCategoryTabMixin from mod controlify] from phase [DEFAULT] in config [controlify.mixins.json] FAILED during APPLY
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:638)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:589)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:379)
	... 41 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Invalid descriptor on controlify.mixins.json:compat.yacl.YACLScreenCategoryTabMixin from mod controlify->@Inject::onConstructCategory(Ldev/isxander/yacl3/gui/YACLScreen;Ldev/isxander/yacl3/api/ConfigCategory;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V! Expected (Ldev/isxander/yacl3/gui/YACLScreen;Ldev/isxander/yacl3/api/ConfigCategory;Lnet/minecraft/class_8030;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V but found (Ldev/isxander/yacl3/gui/YACLScreen;Ldev/isxander/yacl3/api/ConfigCategory;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V [INJECT Applicator Phase -> controlify.mixins.json:compat.yacl.YACLScreenCategoryTabMixin from mod controlify -> Apply Injections ->  -> Inject -> controlify.mixins.json:compat.yacl.YACLScreenCategoryTabMixin from mod controlify->@Inject::onConstructCategory(Ldev/isxander/yacl3/gui/YACLScreen;Ldev/isxander/yacl3/api/ConfigCategory;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V]
	at org.spongepowered.asm.mixin.injection.callback.CallbackInjector.inject(CallbackInjector.java:564)
	at org.spongepowered.asm.mixin.injection.callback.CallbackInjector.inject(CallbackInjector.java:494)
	at org.spongepowered.asm.mixin.injection.code.Injector.inject(Injector.java:277)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.inject(InjectionInfo.java:445)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1377)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1062)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:402)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:327)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:422)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	... 41 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	at dev.isxander.yacl3.gui.YACLScreen.lambda$init$4(YACLScreen.java:89)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.Collections$2.tryAdvance(Collections.java:4853)
	at java.base/java.util.Collections$2.forEachRemaining(Collections.java:4861)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575)
	at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616)
	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:622)
	at java.base/java.util.stream.ReferencePipeline.toList(ReferencePipeline.java:627)
	at dev.isxander.yacl3.gui.YACLScreen.method_25426(YACLScreen.java:90)
	at net.minecraft.class_437.method_25423(class_437.java:298)
	at net.minecraft.class_310.method_1507(class_310.java:1187)
	at dev.isxander.controlify.gui.screen.ControllerCarouselScreen.lambda$init$4(ControllerCarouselScreen.java:95)
	at net.minecraft.class_4185.method_25306(class_4185.java:95)
	at dev.isxander.controlify.screenop.compat.vanilla.AbstractButtonComponentProcessor.overrideControllerButtons(AbstractButtonComponentProcessor.java:20)
	at dev.isxander.controlify.screenop.ScreenProcessor.handleComponentButtonOverride(ScreenProcessor.java:178)
	at dev.isxander.controlify.screenop.ScreenProcessor.onControllerUpdate(ScreenProcessor.java:48)
	at dev.isxander.controlify.Controlify.tickController(Controlify.java:498)
	at dev.isxander.controlify.Controlify.lambda$tick$27(Controlify.java:458)
	at dev.isxander.controlify.utils.ControllerUtils.wrapControllerError(ControllerUtils.java:37)
	at dev.isxander.controlify.Controlify.lambda$tick$28(Controlify.java:457)
	at java.base/java.util.Optional.ifPresent(Optional.java:178)
	at dev.isxander.controlify.Controlify.tick(Controlify.java:456)
	at net.fabricmc.fabric.api.client.event.lifecycle.v1.ClientTickEvents.lambda$static$0(ClientTickEvents.java:34)
	at net.minecraft.class_310.handler$zil000$fabric-lifecycle-events-v1$onStartTick(class_310.java:6772)

-- Affected controller --
Details:
	Controller name: Xbox Controller
	Controller identification: ControllerType[friendlyName=Xbox Controller, mappingId=unmapped, themeId=xbox_one, forceJoystick=false, dontLoad=false]
	Controller type: dev.isxander.controlify.controller.gamepad.GamepadController
Stacktrace:
	at dev.isxander.controlify.utils.ControllerUtils.wrapControllerError(ControllerUtils.java:37)
	at dev.isxander.controlify.Controlify.lambda$tick$28(Controlify.java:457)
	at java.base/java.util.Optional.ifPresent(Optional.java:178)
	at dev.isxander.controlify.Controlify.tick(Controlify.java:456)
	at net.fabricmc.fabric.api.client.event.lifecycle.v1.ClientTickEvents.lambda$static$0(ClientTickEvents.java:34)
	at net.minecraft.class_310.handler$zil000$fabric-lifecycle-events-v1$onStartTick(class_310.java:6772)
	at net.minecraft.class_310.method_1574(class_310.java)
	at net.minecraft.class_310.method_1523(class_310.java:1289)
	at net.minecraft.class_310.method_1514(class_310.java:888)
	at net.minecraft.client.main.Main.main(Main.java:265)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Uptime --
Details:
	JVM uptime: 183.204s
	Wall uptime: 175.634s
	High-res time: 174.765s
	Client ticks: 3451 ticks / 172.550s
Stacktrace:
	at net.minecraft.class_310.method_1587(class_310.java:2564)
	at net.minecraft.class_310.method_54580(class_310.java:995)
	at net.minecraft.class_310.method_1514(class_310.java:908)
	at net.minecraft.client.main.Main.main(Main.java:265)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: vanilla, fabric, controlify, fabric-api, fabric-api-base, fabric-api-lookup-api-v1, fabric-biome-api-v1, fabric-block-api-v1, fabric-block-view-api-v2, fabric-blockrenderlayer-v1, fabric-client-tags-api-v1, fabric-command-api-v1, fabric-command-api-v2, fabric-commands-v0, fabric-containers-v0, fabric-content-registries-v0, fabric-convention-tags-v1, fabric-crash-report-info-v1, fabric-data-attachment-api-v1, fabric-data-generation-api-v1, fabric-dimensions-v1, fabric-entity-events-v1, fabric-events-interaction-v0, fabric-events-lifecycle-v0, fabric-game-rule-api-v1, fabric-item-api-v1, fabric-item-group-api-v1, fabric-key-binding-api-v1, fabric-keybindings-v0, fabric-lifecycle-events-v1, fabric-loot-api-v2, fabric-message-api-v1, fabric-mining-level-api-v1, fabric-model-loading-api-v1, fabric-models-v0, fabric-networking-api-v1, fabric-object-builder-api-v1, fabric-particles-v1, fabric-recipe-api-v1, fabric-registry-sync-v0, fabric-renderer-api-v1, fabric-renderer-indigo, fabric-renderer-registries-v1, fabric-rendering-data-attachment-v1, fabric-rendering-fluids-v1, fabric-rendering-v0, fabric-rendering-v1, fabric-resource-conditions-api-v1, fabric-resource-loader-v0, fabric-screen-api-v1, fabric-screen-handler-api-v1, fabric-sound-api-v1, fabric-transfer-api-v1, fabric-transitive-access-wideners-v1, fabricloader, modmenu, yet_another_config_lib_v3

-- System Details --
Details:
	Minecraft Version: 1.20.4
	Minecraft Version ID: 1.20.4
	Operating System: Mac OS X (aarch64) version 14.4.1
	Java Version: 17.0.8, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 646600408 bytes (616 MiB) / 1719664640 bytes (1640 MiB) up to 6408896512 bytes (6112 MiB)
	CPUs: 8
	Processor Vendor: Apple Inc.
	Processor Name: Apple M2
	Identifier: Apple Inc. Family 0xda33d83d Model 0 Stepping 0
	Microarchitecture: ARM64 SoC: Avalanche + Blizzard
	Frequency (GHz): 3.50
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 8
	Graphics card #0 name: Apple M2
	Graphics card #0 vendor: Apple (0x106b)
	Graphics card #0 VRAM (MB): 0.00
	Graphics card #0 deviceId: unknown
	Graphics card #0 versionInfo: unknown
	Memory slot #0 capacity (MB): 0.00
	Memory slot #0 clockSpeed (GHz): 0.00
	Memory slot #0 type: unknown
	Virtual memory max (MB): 10240.00
	Virtual memory used (MB): 7285.81
	Swap memory total (MB): 2048.00
	Swap memory used (MB): 770.31
	JVM Flags: 2 total; -Xmx6112m -Xms256m
	Fabric Mods: 
		controlify: Controlify 1.8.1+1.20.4
			dev_isxander_libsdl4j: libsdl4j 2.28.2-11
			org_hid4java_hid4java: hid4java 0.7.0
			org_quiltmc_quilt-json5: quilt-json5 1.0.3
		fabric-api: Fabric API 0.97.1+1.20.4
			fabric-api-base: Fabric API Base 0.4.37+78d798af4f
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.50+82b1bb3e4f
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.17+78d798af4f
			fabric-block-api-v1: Fabric Block API (v1) 1.0.17+3e2216cb4f
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.5+78d798af4f
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.47+78d798af4f
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.8+78d798af4f
			fabric-command-api-v1: Fabric Command API (v1) 1.2.42+f71b366f4f
			fabric-command-api-v2: Fabric Command API (v2) 2.2.21+78d798af4f
			fabric-commands-v0: Fabric Commands (v0) 0.2.59+df3654b34f
			fabric-containers-v0: Fabric Containers (v0) 0.1.87+df3654b34f
			fabric-content-registries-v0: Fabric Content Registries (v0) 5.0.16+78d798af4f
			fabric-convention-tags-v1: Fabric Convention Tags 1.5.11+78d798af4f
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.24+78d798af4f
			fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.1.5+b90db5744f
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 13.2.5+5c0133444f
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.63+6605d1a84f
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.6.2+09fc25014f
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.7.2+389931eb4f
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.75+df3654b34f
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.47+78d798af4f
			fabric-item-api-v1: Fabric Item API (v1) 2.3.0+bcdd12964f
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.27+ee30b13a4f
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.42+78d798af4f
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.40+df3654b34f
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.3.1+a67ffb5d4f
			fabric-loot-api-v2: Fabric Loot API (v2) 2.1.10+78d798af4f
			fabric-message-api-v1: Fabric Message API (v1) 6.0.6+78d798af4f
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.66+78d798af4f
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 1.0.9+78d798af4f
			fabric-models-v0: Fabric Models (v0) 0.4.8+9386d8a74f
			fabric-networking-api-v1: Fabric Networking API (v1) 3.1.8+2e5ac5484f
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 13.1.0+dba1195c4f
			fabric-particles-v1: Fabric Particles (v1) 1.1.8+78d798af4f
			fabric-recipe-api-v1: Fabric Recipe API (v1) 2.0.21+78d798af4f
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 4.0.20+ee30b13a4f
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.2.5+78d798af4f
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.5.6+d331d3144f
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.54+df3654b34f
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.43+73761d2e4f
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.1.2+e761c6694f
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.57+df3654b34f
			fabric-rendering-v1: Fabric Rendering (v1) 3.2.1+6fd945a04f
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.15+78d798af4f
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.21+ee30b13a4f
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.18+78d798af4f
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.56+78d798af4f
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.18+78d798af4f
			fabric-transfer-api-v1: Fabric Transfer API (v1) 4.0.12+90f2d7b14f
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 5.0.15+78d798af4f
		fabricloader: Fabric Loader 0.15.11
			mixinextras: MixinExtras 0.3.5
		java: OpenJDK 64-Bit Server VM 17
		minecraft: Minecraft 1.20.4
		modmenu: Mod Menu 9.2.0
		placeholder-api: Placeholder API 2.4.0-pre.1+1.20.4
		yet_another_config_lib_v3: YetAnotherConfigLib 3.5.0+1.20.4-fabric
			com_twelvemonkeys_common_common-image: common-image 3.10.0
			com_twelvemonkeys_common_common-io: common-io 3.10.0
			com_twelvemonkeys_common_common-lang: common-lang 3.10.0
			com_twelvemonkeys_imageio_imageio-core: imageio-core 3.10.0
			com_twelvemonkeys_imageio_imageio-metadata: imageio-metadata 3.10.0
			com_twelvemonkeys_imageio_imageio-webp: imageio-webp 3.10.0
			org_quiltmc_parsers_gson: gson 0.2.1
			org_quiltmc_parsers_json: json 0.2.1
	Launched Version: fabric-loader-0.15.11-1.20.4
	Launcher name: minecraft-launcher
	Backend library: LWJGL version 3.3.2-snapshot
	Backend API: Apple M2 GL version 4.1 Metal - 88, Apple
	Window size: 2940x1840
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: <disabled>
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Universe: 400921fb54442d18
	Type: Client (map_client.txt)
	GPU Warnings: version: Metal
	Graphics mode: fancy
	Render Distance: 12/12 chunks
	Resource Packs: fabric, controlify, fabric-api, fabric-api-base, fabric-api-lookup-api-v1, fabric-biome-api-v1, fabric-block-api-v1, fabric-block-view-api-v2, fabric-blockrenderlayer-v1, fabric-client-tags-api-v1, fabric-command-api-v1, fabric-command-api-v2, fabric-commands-v0, fabric-containers-v0, fabric-content-registries-v0, fabric-convention-tags-v1, fabric-crash-report-info-v1, fabric-data-attachment-api-v1, fabric-data-generation-api-v1, fabric-dimensions-v1, fabric-entity-events-v1, fabric-events-interaction-v0, fabric-events-lifecycle-v0, fabric-game-rule-api-v1, fabric-item-api-v1, fabric-item-group-api-v1, fabric-key-binding-api-v1, fabric-keybindings-v0, fabric-lifecycle-events-v1, fabric-loot-api-v2, fabric-message-api-v1, fabric-mining-level-api-v1, fabric-model-loading-api-v1, fabric-models-v0, fabric-networking-api-v1, fabric-object-builder-api-v1, fabric-particles-v1, fabric-recipe-api-v1, fabric-registry-sync-v0, fabric-renderer-api-v1, fabric-renderer-indigo, fabric-renderer-registries-v1, fabric-rendering-data-attachment-v1, fabric-rendering-fluids-v1, fabric-rendering-v0, fabric-rendering-v1, fabric-resource-conditions-api-v1, fabric-resource-loader-v0, fabric-screen-api-v1, fabric-screen-handler-api-v1, fabric-sound-api-v1, fabric-transfer-api-v1, fabric-transitive-access-wideners-v1, fabricloader, modmenu, modmenu_programmer_art, modmenu_high_contrast
	Current Language: en_us
	Locale: en_US
	CPU: 8x Apple M2
```

### Mod Version

1.8.1

### Controller

issues

### Bluetooth

- [X] Yes

### Operating System

macOS

### ARM

- [ ] Yes

### Just to make sure...

- [X] I have made sure I am using the latest version of Controlify for the latest version of Minecraft.
- [X] I have made sure there are no other issues describing the same problem on the [issue tracker](https://github.com/isXander/Controlify/issues).

**Comment by bmward4** [comment]
Same. On macOS running Fabric through forge with no other mods.

**Comment by BleyChimera** [comment]
Same. Both on the Steam deck and on a Windows machine.

**Comment by DeezNuts12-21** [comment]
Also

**Comment by Dimmidice** [comment]
Also having this issue on 1.20.1 fabric. even with only controlify (& supporting addons) installed 

> The game crashed whilst mouseclicked event handler
Error: java.lang.RuntimeException: Mixin transformation of dev.isxander.yacl3.gui.YACLScreen$CategoryTab failed

**Comment by isXander** [comment]
Closing as this appears to be resolved — reopen if you're still seeing this

**Comment by TaxiPone** [comment]
has this been resolved? How? All the 21.11 versions are still causing this for me.
Fabric 0.19.2 // Windows 11

>>> [06:14:31] [ForkJoinPool-1-worker-9/WARN]: Mod dev_isxander_libsdl4j uses the version 3.2.18.release-3.2.18-79 which isn't compatible with Loader's extended semantic version format (Could not parse version number component 'release'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
