### ISSUE TITLE
[Bug] Mod will stop tracking Steam Deck

### ISSUE THREAD

**Issue by CoderMonkey1956** [isXander/Controlify#473]
### Current Behaviour

Basicly in some cases the mod will just completely break. In the video keep in mind a few things:

1. I never touched any of the joysticks during the video
2. All controller buttons did not work
3. I was turning with gyro/trackpad controls

https://youtu.be/L7LPSUjlA_c

### Expected Behaviour

The controller would work properly

### Reproduction Steps

idk

### Mod Version

v2.0.0-beta.21+1.21-fabric

### Controller

Steam Deck

### Bluetooth

- [ ] Yes

### Operating System

Linux/SteamOS

### ARM

- [ ] Yes

### Just to make sure...

- [X] I have made sure I am using the latest version of Controlify for the latest version of Minecraft.
- [X] I have made sure there are no other issues describing the same problem on the [issue tracker](https://github.com/isXander/Controlify/issues).

**Comment by CoderMonkey1956** [comment]
@isXander I think it also has to do with this messege from the logs: 

[10:48:43] [HttpClient-2-Worker-2/INFO]: [STDOUT]: Received message with no pending eval: {"id":387556,"result":{"result":{"type":"string","value":"{\"unControllerIndex\":15,\"unPacketNum\":80351,\"ulUpperButtons\":16384,\"ulButtons\":0,\"sLeftPadX\":0,\"sLeftPadY\":0,\"sRightPadX\":0,\"sRightPadY\":0,\"sCenterPadX\":0,\"sCenterPadY\":0,\"sLeftStickX\":44,\"sLeftStickY\":-32767,\"sRightStickX\":84,\"sRightStickY\":449,\"sTriggerL\":0,\"sTriggerR\":0,\"flHardwareQuatW\":-0.8960797190666199,\"flHardwareQuatX\":0.1468227505683899,\"flHardwareQuatY\":0.028956390917301178,\"flHardwareQuatZ\":0.4179063141345978,\"flHardwareGyroDegreesPerSecondPitch\":-1.0986663103103638,\"flHardwareGyroDegreesPerSecondYaw\":0,\"flHardwareGyroDegreesPerSecondRoll\":-0.1831110566854477,\"flAccelerometerNoiseLength\":3.9549872875213623,\"flGyroNoiseLength\":0.44329285621643066,\"flGyroCalibrationProgress\":0.0062500000931322575,\"flSoftwareQuatW\":0.8982782959938049,\"flSoftwareQuatX\":-0.13748879730701447,\"flSoftwareQuatY\":-0.039150871336460114,\"flSoftwareQuatZ\":-0.4155239164829254,\"flSoftwareGyroDegreesPerSecondPitch\":-0.3412612974643707,\"flSoftwareGyroDegreesPerSecondYaw\":-0.007296526338905096,\"flSoftwareGyroDegreesPerSecondRoll\":-0.027054596692323685,\"flGravityVectorX\":0.09760117530822754,\"flGravityVectorY\":0.7768418192863464,\"flGravityVectorZ\":0.634499192237854,\"flTrustedGravityVectorX\":0.1042342260479927,\"flTrustedGravityVectorY\":0.7917265295982361,\"flTrustedGravityVectorZ\":0.6167359948158264,\"sBatteryLevel\":0,\"sPressurePadLeft\":0,\"sPressurePadRight\":0,\"sPressureBumperLeft\":0,\"sPressureBumperRight\":0,\"unHardwareUpdateInMicrosec\":4000}"}}}
[10:48:44] [Steam Deck Poller/ERROR]: Uncaught exception in thread "Steam Deck Poller"
java.util.concurrent.CompletionException: java.util.concurrent.TimeoutException
	at java.base/java.util.concurrent.CompletableFuture.reportJoin(CompletableFuture.java:413) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture.join(CompletableFuture.java:2118) ~[?:?]
	at dev.isxander.controlify.driver.steamdeck.SteamDeckDriver.lambda$ensurePolling$0(SteamDeckDriver.java:88) ~[controlify-2.0.0-beta.211.21-fabric.i0:0/:?]
	at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: java.util.concurrent.TimeoutException
	at java.base/java.util.concurrent.CompletableFuture$Timeout.run(CompletableFuture.java:2920) ~[?:?]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572) ~[?:?]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317) ~[?:?]
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	... 1 more

**Comment by CoderMonkey1956** [comment]
[logmessege.txt](https://github.com/user-attachments/files/18231680/logmessege.txt)
