### ISSUE TITLE
[Bug] controlify crash after scrolling to bottom of mod menu

### ISSUE THREAD

**Issue by ccn0** [isXander/Controlify#489]
### Current Behaviour

when i scrolled to the bottom of the mod menu list of mods, when i reached the bottom and scrolled again, it said saving world and crashed.

### Expected Behaviour

it probably shouldnt have tried to scroll to the next item even if there wasnt one, i'd expect it to do nothing if i scrolled down at the bottom or wrap around

### Reproduction Steps

1. open mod menu
2. use controller to scroll to very bottom
3. scroll once more

### Logs

```shell
---- Minecraft Crash Report ----
// Why did you do that?

Time: 2024-12-30 07:05:45
Description: Ticking current controller

java.lang.NullPointerException: Cannot invoke "com.terraformersmc.modmenu.gui.widget.entries.ModListEntry.getMod()" because "entry" is null
	at knot//com.terraformersmc.modmenu.gui.widget.ModListWidget.setSelected(ModListWidget.java:83)
	at knot//com.terraformersmc.modmenu.gui.widget.ModListWidget.method_25313(ModListWidget.java:27)
	at knot//net.minecraft.class_4280.method_48205(class_4280.java:37)
	at knot//net.minecraft.class_4069.method_48205(class_4069.java:128)
	at knot//dev.isxander.controlify.screenop.ScreenProcessor.handleComponentNavigation(ScreenProcessor.java:153)
	at knot//dev.isxander.controlify.screenop.ScreenProcessor.onControllerUpdate(ScreenProcessor.java:54)
	at knot//dev.isxander.controlify.Controlify.tickController(Controlify.java:610)
	at knot//dev.isxander.controlify.Controlify.lambda$tick$41(Controlify.java:550)
	at knot//dev.isxander.controlify.utils.ControllerUtils.wrapControllerError(ControllerUtils.java:27)
	at knot//dev.isxander.controlify.Controlify.lambda$tick$42(Controlify.java:549)
	at java.base/java.util.Optional.ifPresent(Optional.java:178)
	at knot//dev.isxander.controlify.Controlify.tick(Controlify.java:548)
	at knot//net.fabricmc.fabric.api.client.event.lifecycle.v1.ClientTickEvents.lambda$static$0(ClientTickEvents.java:34)
	at knot//net.minecraft.class_310.handler$bcf000$fabric-lifecycle-events-v1$onStartTick(class_310.java:11576)
	at knot//net.minecraft.class_310.method_1574(class_310.java)
	at knot//net.minecraft.class_310.method_1523(class_310.java:1302)
	at knot//net.minecraft.class_310.method_1514(class_310.java:922)
	at knot//net.minecraft.client.main.Main.main(Main.java:267)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:243)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:278)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at knot//com.terraformersmc.modmenu.gui.widget.ModListWidget.setSelected(ModListWidget.java:83)
	at knot//com.terraformersmc.modmenu.gui.widget.ModListWidget.method_25313(ModListWidget.java:27)
	at knot//net.minecraft.class_4280.method_48205(class_4280.java:37)
	at knot//net.minecraft.class_4069.method_48205(class_4069.java:128)
	at knot//dev.isxander.controlify.screenop.ScreenProcessor.handleComponentNavigation(ScreenProcessor.java:153)
	at knot//dev.isxander.controlify.screenop.ScreenProcessor.onControllerUpdate(ScreenProcessor.java:54)
	at knot//dev.isxander.controlify.Controlify.tickController(Controlify.java:610)
	at knot//dev.isxander.controlify.Controlify.lambda$tick$41(Controlify.java:550)
	at knot//dev.isxander.controlify.utils.ControllerUtils.wrapControllerError(ControllerUtils.java:27)
	at knot//dev.isxander.controlify.Controlify.lambda$tick$42(Controlify.java:549)
	at java.base/java.util.Optional.ifPresent(Optional.java:178)
	at knot//dev.isxander.controlify.Controlify.tick(Controlify.java:548)
	at knot//net.fabricmc.fabric.api.client.event.lifecycle.v1.ClientTickEvents.lambda$static$0(ClientTickEvents.java:34)
	at knot//net.minecraft.class_310.handler$bcf000$fabric-lifecycle-events-v1$onStartTick(class_310.java:11576)

-- Affected controller --
Details:
	Controller name: dualsense
	Controller identification: DualSense Controller
	Controller type: dev.isxander.controlify.controller.ControllerEntity
Stacktrace:
	at knot//dev.isxander.controlify.utils.ControllerUtils.wrapControllerError(ControllerUtils.java:27)
	at knot//dev.isxander.controlify.Controlify.lambda$tick$42(Controlify.java:549)
	at java.base/java.util.Optional.ifPresent(Optional.java:178)
	at knot//dev.isxander.controlify.Controlify.tick(Controlify.java:548)
	at knot//net.fabricmc.fabric.api.client.event.lifecycle.v1.ClientTickEvents.lambda$static$0(ClientTickEvents.java:34)
	at knot//net.minecraft.class_310.handler$bcf000$fabric-lifecycle-events-v1$onStartTick(class_310.java:11576)
	at knot//net.minecraft.class_310.method_1574(class_310.java)
	at knot//net.minecraft.class_310.method_1523(class_310.java:1302)
	at knot//net.minecraft.class_310.method_1514(class_310.java:922)
	at knot//net.minecraft.client.main.Main.main(Main.java:267)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:243)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:278)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

-- Uptime --
Details:
	JVM uptime: 1000.524s
	Wall uptime: 968.958s
	High-res time: 961.800s
	Client ticks: 18767 ticks / 938.350s
Stacktrace:
	at knot//net.minecraft.class_310.method_1587(class_310.java:2371)
	at knot//net.minecraft.class_310.method_54580(class_310.java:991)
	at knot//net.minecraft.class_310.method_1514(class_310.java:943)
	at knot//net.minecraft.client.main.Main.main(Main.java:267)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:243)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:278)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

-- Affected level --
Details:
	All players: 1 total; [class_746['playerplayerplayer'/35, l='ClientLevel', x=-188.51, y=70.00, z=365.37]]
	Chunk stats: 1521, 1057
	Level dimension: minecraft:overworld
	Level spawn location: World: (192,73,112), Section: (at 0,9,0 in 12,4,7; chunk contains blocks 192,-64,112 to 207,319,127), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 22569918 game time, 35218752 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
	Tracked entity count: 431

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: vanilla, fabric, bobby, cloth-config, continuity, controlify, dynamic_fps, entity_model_features, entity_texture_features, entityculling, fabric-api, fabric-api-base, fabric-api-lookup-api-v1, fabric-biome-api-v1, fabric-block-api-v1, fabric-block-view-api-v2, fabric-blockrenderlayer-v1, fabric-client-tags-api-v1, fabric-command-api-v1, fabric-command-api-v2, fabric-commands-v0, fabric-content-registries-v0, fabric-convention-tags-v1, fabric-convention-tags-v2, fabric-crash-report-info-v1, fabric-data-attachment-api-v1, fabric-data-generation-api-v1, fabric-dimensions-v1, fabric-entity-events-v1, fabric-events-interaction-v0, fabric-game-rule-api-v1, fabric-item-api-v1, fabric-item-group-api-v1, fabric-key-binding-api-v1, fabric-keybindings-v0, fabric-language-kotlin, fabric-lifecycle-events-v1, fabric-loot-api-v2, fabric-loot-api-v3, fabric-message-api-v1, fabric-model-loading-api-v1, fabric-networking-api-v1, fabric-object-builder-api-v1, fabric-particles-v1, fabric-recipe-api-v1, fabric-registry-sync-v0, fabric-renderer-api-v1, fabric-renderer-indigo, fabric-rendering-data-attachment-v1, fabric-rendering-fluids-v1, fabric-rendering-v1, fabric-resource-conditions-api-v1, fabric-resource-loader-v0, fabric-screen-api-v1, fabric-screen-handler-api-v1, fabric-sound-api-v1, fabric-tag-api-v1, fabric-transfer-api-v1, fabric-transitive-access-wideners-v1, fabricloader, gammautils, lambdynlights, lambdynlights_api, libipn, litematica, lithium, malilib, modmenu, notenoughanimations, placeholder-api, pride, reeses-sodium-options, roughlyenoughitems, shulkerboxtooltip, sodium, sodium-extra, spruceui, tweakeroo, xaerominimap, xaeroworldmap, yet_another_config_lib_v3, zoomify, continuity:default, continuity:glass_pane_culling_fix, file/FreshAnimations_v1.9.3.zip, file/LowOnFire 1.21.3.zip, file/plus400SPITVanillaTweaks_r367393_MC1.21.x.zip, file/§eExtended_Illumina_NEA_1.21x.zip
```

### Mod Version

2.0.0-beta.21+1.21.4-fabric

### Controller

dualsense

### Bluetooth

- [ ] Yes

### Operating System

Windows

### ARM

- [X] Yes

### Additional Information

i dont know if this is a controlify issue or a modmenu issue, but it said 'Description: Ticking current controller' so here i am

### Just to make sure...

- [X] I have made sure I am using the latest version of Controlify for the latest version of Minecraft.
- [X] I have made sure there are no other issues describing the same problem on the [issue tracker](https://github.com/isXander/Controlify/issues).

**Comment by ccn0** [comment]
this was a bug in Mod Menu, where if you scrolled to the bottom, it would crash. this is not a controlify issue.
