### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by luphoria** [isXander/Controlify#80]
**Describe the bug**
Attempting to start Minecraft v1.19.4 via Prism Launcher with the mods:
 - Controlify
 - Iris
 - Sodium
 - YetAnotherConfigLib

results in a crash.

**To Reproduce**
1. Download Prism Launcher
2. Set up v1.19.4 and install the mods "Controlify," "Iris," "Sodium," "YetAnotherConfigLib"
3. Start Minecraft
4. crash!

**Expected behavior**
Minecraft starts with the mods enabled.

**Screenshots**
Here's a screenshot of my enabled mods and their respective versions:
![image](https://github.com/isXander/Controlify/assets/60309933/62605f30-f007-48da-a5dd-2363862ff5e8)

**Minecraft Info (please complete the following information):**
 - OS: Arch Linux (instantOS, on Steam Deck)
 - Minecraft Version: 1.19.4
 - Mod Version: 1.2.1+1.19.4

**Additional context**
Crash log!
```
---- Minecraft Crash Report ----
// Why is it breaking :(

Time: 2023-05-28 18:15:49
Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'controlify'!
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:53)
	at net.minecraft.class_310.<init>(class_310.java:468)
	at net.minecraft.client.main.Main.main(Main.java:198)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71)
Caused by: java.lang.ExceptionInInitializerError
	at dev.isxander.controlify.Controlify.preInitialiseControlify(Controlify.java:201)
	at dev.isxander.controlify.ControlifyEntrypoint.onInitializeClient(ControlifyEntrypoint.java:8)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
	... 10 more
Caused by: java.lang.IllegalStateException: Registry is already frozen (trying to add key ResourceKey[minecraft:sound_event / controlify:controlify.ui.focus])
	at net.minecraft.class_2370.method_40274(class_2370.java:135)
	at net.minecraft.class_2370.method_46744(class_2370.java:141)
	at net.minecraft.class_2370.method_10272(class_2370.java:186)
	at net.minecraft.class_2378.method_39197(class_2378.java:118)
	at net.minecraft.class_2378.method_10230(class_2378.java:114)
	at dev.isxander.controlify.sound.ControlifySounds.register(ControlifySounds.java:14)
	at dev.isxander.controlify.sound.ControlifySounds.<clinit>(ControlifySounds.java:10)
	... 13 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:53)
	at net.minecraft.class_310.<init>(class_310.java:468)

-- Initialization --
Details:
	Modules: 
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:198)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71)

-- System Details --
Details:
	Minecraft Version: 1.19.4
	Minecraft Version ID: 1.19.4
	Operating System: Linux (amd64) version 6.1.28-1-lts
	Java Version: 17.0.7, N/A
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 174313136 bytes (166 MiB) / 536870912 bytes (512 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 8
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Custom APU 0405
	Identifier: AuthenticAMD Family 23 Model 144 Stepping 2
	Microarchitecture: unknown
	Frequency (GHz): 2.80
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: VanGogh [AMD Custom GPU 0405]
	Graphics card #0 vendor: Advanced Micro Devices, Inc. [AMD/ATI] (0x1002)
	Graphics card #0 VRAM (MB): 258.00
	Graphics card #0 deviceId: 0x163f
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 8183.36
	Virtual memory used (MB): 4909.16
	Swap memory total (MB): 767.99
	Swap memory used (MB): 416.45
	JVM Flags: 2 total; -Xms512m -Xmx4096m
	Launched Version: 1.19.4
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: Unknown
	Window size: <not initialized>
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: <disabled>
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	CPU: <unknown>
```

**Comment by isXander** [comment]
Fabric API?

**Comment by itsarobin** [comment]
I can confirm that adding Fabric API to the mod list of the OP's prism launcher config will fix this crash

**Comment by luphoria** [comment]
Thank you, I feel a little silly. 😅 Although, why isn't this in the required mod list?
